// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/request/common.proto (package youtube.request.common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.request.common.Request
 */
export const Request = proto3.makeMessageType(
  "youtube.request.common.Request",
  () => [
    { no: 1, name: "context", kind: "message", T: Context },
  ],
);

/**
 * @generated from message youtube.request.common.Context
 */
export const Context = proto3.makeMessageType(
  "youtube.request.common.Context",
  () => [
    { no: 9, name: "adSignalsInfo", kind: "message", T: AdSignalsInfo },
  ],
);

/**
 * @generated from message youtube.request.common.AdSignalsInfo
 */
export const AdSignalsInfo = proto3.makeMessageType(
  "youtube.request.common.AdSignalsInfo",
  () => [
    { no: 1, name: "params", kind: "message", T: Params, repeated: true },
  ],
);

/**
 * @generated from message youtube.request.common.Params
 */
export const Params = proto3.makeMessageType(
  "youtube.request.common.Params",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

