// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/request/common.proto (package youtube.request.common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.request.common.Request
 */
export declare class Request extends Message<Request> {
  /**
   * @generated from field: youtube.request.common.Context context = 1;
   */
  context?: Context;

  constructor(data?: PartialMessage<Request>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.common.Request";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Request;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Request;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Request;

  static equals(a: Request | PlainMessage<Request> | undefined, b: Request | PlainMessage<Request> | undefined): boolean;
}

/**
 * @generated from message youtube.request.common.Context
 */
export declare class Context extends Message<Context> {
  /**
   * @generated from field: youtube.request.common.AdSignalsInfo adSignalsInfo = 9;
   */
  adSignalsInfo?: AdSignalsInfo;

  constructor(data?: PartialMessage<Context>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.common.Context";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Context;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Context;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Context;

  static equals(a: Context | PlainMessage<Context> | undefined, b: Context | PlainMessage<Context> | undefined): boolean;
}

/**
 * @generated from message youtube.request.common.AdSignalsInfo
 */
export declare class AdSignalsInfo extends Message<AdSignalsInfo> {
  /**
   * @generated from field: repeated youtube.request.common.Params params = 1;
   */
  params: Params[];

  constructor(data?: PartialMessage<AdSignalsInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.common.AdSignalsInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdSignalsInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdSignalsInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdSignalsInfo;

  static equals(a: AdSignalsInfo | PlainMessage<AdSignalsInfo> | undefined, b: AdSignalsInfo | PlainMessage<AdSignalsInfo> | undefined): boolean;
}

/**
 * @generated from message youtube.request.common.Params
 */
export declare class Params extends Message<Params> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;

  constructor(data?: PartialMessage<Params>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.request.common.Params";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params;

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean;
}

