// @generated by protobuf-ts 2.9.0 with parameter output_javascript_es2019
// @generated from protobuf file "protos/viewUnite.proto" (package "viewunite.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Any } from "../google/protobuf/any";
/**
 * @generated from protobuf message viewunite.v1.RelateCard
 */
export interface RelateCard {
    /**
     * @generated from protobuf field: viewunite.v1.RelateCardType relate_card_type = 1;
     */
    relateCardType: RelateCardType;
}
/**
 * @generated from protobuf message viewunite.v1.Relates
 */
export interface Relates {
    /**
     * @generated from protobuf field: repeated viewunite.v1.RelateCard cards = 1;
     */
    cards: RelateCard[];
}
/**
 * @generated from protobuf message viewunite.v1.CommonModule
 */
export interface CommonModule {
    /**
     * @generated from protobuf field: viewunite.v1.ModuleType type = 1;
     */
    type: ModuleType;
    /**
     * @generated from protobuf oneof: data
     */
    data: {
        oneofKind: "relates";
        /**
         * @generated from protobuf field: viewunite.v1.Relates relates = 22;
         */
        relates: Relates;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message viewunite.v1.IntroductionTab
 */
export interface IntroductionTab {
    /**
     * @generated from protobuf field: string title = 1;
     */
    title: string;
    /**
     * @generated from protobuf field: repeated viewunite.v1.CommonModule modules = 2;
     */
    modules: CommonModule[];
}
/**
 * @generated from protobuf message viewunite.v1.TabModule
 */
export interface TabModule {
    /**
     * @generated from protobuf field: viewunite.v1.TabType tab_type = 1;
     */
    tabType: TabType;
    /**
     * @generated from protobuf oneof: tab
     */
    tab: {
        oneofKind: "introduction";
        /**
         * @generated from protobuf field: viewunite.v1.IntroductionTab introduction = 2;
         */
        introduction: IntroductionTab;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message viewunite.v1.Tab
 */
export interface Tab {
    /**
     * @generated from protobuf field: repeated viewunite.v1.TabModule tab_module = 1;
     */
    tabModule: TabModule[];
}
/**
 * @generated from protobuf message viewunite.v1.CM
 */
export interface CM {
    /**
     * @generated from protobuf field: google.protobuf.Any cm_under_player = 1;
     */
    cmUnderPlayer?: Any;
    /**
     * @generated from protobuf field: google.protobuf.Any ads_control = 2;
     */
    adsControl?: Any;
    /**
     * @generated from protobuf field: repeated google.protobuf.Any source_content = 3;
     */
    sourceContent: Any[];
}
/**
 * @generated from protobuf message viewunite.v1.ViewUniteReply
 */
export interface ViewUniteReply {
    /**
     * @generated from protobuf field: viewunite.v1.Tab tab = 5;
     */
    tab?: Tab;
    /**
     * @generated from protobuf field: viewunite.v1.CM cm = 7;
     */
    cm?: CM;
}
/**
 * @generated from protobuf enum viewunite.v1.TabType
 */
export declare enum TabType {
    /**
     * @generated from protobuf enum value: TAB_NONE = 0;
     */
    TAB_NONE = 0,
    /**
     * 详情 Tab
     *
     * @generated from protobuf enum value: TAB_INTRODUCTION = 1;
     */
    TAB_INTRODUCTION = 1,
    /**
     * 评论区 Tab
     *
     * @generated from protobuf enum value: TAB_REPLY = 2;
     */
    TAB_REPLY = 2,
    /**
     * OGV 活动信息 Tab
     *
     * @generated from protobuf enum value: TAB_OGV_ACTIVITY = 3;
     */
    TAB_OGV_ACTIVITY = 3
}
/**
 * @generated from protobuf enum viewunite.v1.ModuleType
 */
export declare enum ModuleType {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: OGV_INTRODUCTION = 1;
     */
    OGV_INTRODUCTION = 1,
    /**
     * @generated from protobuf enum value: OGV_TITLE = 2;
     */
    OGV_TITLE = 2,
    /**
     * @generated from protobuf enum value: UGC_HEADLINE = 3;
     */
    UGC_HEADLINE = 3,
    /**
     * @generated from protobuf enum value: UGC_INTRODUCTION = 4;
     */
    UGC_INTRODUCTION = 4,
    /**
     * @generated from protobuf enum value: KING_POSITION = 5;
     */
    KING_POSITION = 5,
    /**
     * @generated from protobuf enum value: MASTER_USER_LIST = 6;
     */
    MASTER_USER_LIST = 6,
    /**
     * @generated from protobuf enum value: STAFFS = 7;
     */
    STAFFS = 7,
    /**
     * @generated from protobuf enum value: HONOR = 8;
     */
    HONOR = 8,
    /**
     * @generated from protobuf enum value: OWNER = 9;
     */
    OWNER = 9,
    /**
     * @generated from protobuf enum value: PAGE = 10;
     */
    PAGE = 10,
    /**
     * @generated from protobuf enum value: ACTIVITY_RESERVE = 11;
     */
    ACTIVITY_RESERVE = 11,
    /**
     * @generated from protobuf enum value: LIVE_ORDER = 12;
     */
    LIVE_ORDER = 12,
    /**
     * @generated from protobuf enum value: POSITIVE = 13;
     */
    POSITIVE = 13,
    /**
     * @generated from protobuf enum value: SECTION = 14;
     */
    SECTION = 14,
    /**
     * @generated from protobuf enum value: RELATE = 15;
     */
    RELATE = 15,
    /**
     * @generated from protobuf enum value: PUGV = 16;
     */
    PUGV = 16,
    /**
     * @generated from protobuf enum value: COLLECTION_CARD = 17;
     */
    COLLECTION_CARD = 17,
    /**
     * @generated from protobuf enum value: ACTIVITY = 18;
     */
    ACTIVITY = 18,
    /**
     * @generated from protobuf enum value: CHARACTER = 19;
     */
    CHARACTER = 19,
    /**
     * @generated from protobuf enum value: FOLLOW_LAYER = 20;
     */
    FOLLOW_LAYER = 20,
    /**
     * @generated from protobuf enum value: OGV_SEASONS = 21;
     */
    OGV_SEASONS = 21,
    /**
     * @generated from protobuf enum value: UGC_SEASON = 22;
     */
    UGC_SEASON = 22,
    /**
     * @generated from protobuf enum value: OGV_LIVE_RESERVE = 23;
     */
    OGV_LIVE_RESERVE = 23,
    /**
     * @generated from protobuf enum value: COMBINATION_EPISODE = 24;
     */
    COMBINATION_EPISODE = 24,
    /**
     * @generated from protobuf enum value: SPONSOR = 25;
     */
    SPONSOR = 25,
    /**
     * @generated from protobuf enum value: ACTIVITY_ENTRANCE = 26;
     */
    ACTIVITY_ENTRANCE = 26,
    /**
     * @generated from protobuf enum value: THEATRE_HOT_TOPIC = 27;
     */
    THEATRE_HOT_TOPIC = 27,
    /**
     * @generated from protobuf enum value: RELATED_RECOMMEND = 28;
     */
    RELATED_RECOMMEND = 28,
    /**
     * @generated from protobuf enum value: PAY_BAR = 29;
     */
    PAY_BAR = 29,
    /**
     * @generated from protobuf enum value: BANNER = 30;
     */
    BANNER = 30,
    /**
     * @generated from protobuf enum value: AUDIO = 31;
     */
    AUDIO = 31,
    /**
     * @generated from protobuf enum value: AGG_CARD = 32;
     */
    AGG_CARD = 32,
    /**
     * @generated from protobuf enum value: SINGLE_EP = 33;
     */
    SINGLE_EP = 33,
    /**
     * @generated from protobuf enum value: LIKE_COMMENT = 34;
     */
    LIKE_COMMENT = 34,
    /**
     * @generated from protobuf enum value: ATTENTION_RECOMMEND = 35;
     */
    ATTENTION_RECOMMEND = 35,
    /**
     * @generated from protobuf enum value: COVENANTER = 36;
     */
    COVENANTER = 36
}
/**
 * @generated from protobuf enum viewunite.v1.RelateCardType
 */
export declare enum RelateCardType {
    /**
     * @generated from protobuf enum value: CARD_TYPE_UNKNOWN = 0;
     */
    CARD_TYPE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: AV = 1;
     */
    AV = 1,
    /**
     * @generated from protobuf enum value: BANGUMI = 2;
     */
    BANGUMI = 2,
    /**
     * @generated from protobuf enum value: RESOURCE = 3;
     */
    RESOURCE = 3,
    /**
     * @generated from protobuf enum value: GAME = 4;
     */
    GAME = 4,
    /**
     * @generated from protobuf enum value: CM_TYPE = 5;
     */
    CM_TYPE = 5,
    /**
     * @generated from protobuf enum value: LIVE = 6;
     */
    LIVE = 6,
    /**
     * @generated from protobuf enum value: AI_RECOMMEND = 7;
     */
    AI_RECOMMEND = 7,
    /**
     * @generated from protobuf enum value: BANGUMI_AV = 8;
     */
    BANGUMI_AV = 8,
    /**
     * @generated from protobuf enum value: BANGUMI_UGC = 9;
     */
    BANGUMI_UGC = 9,
    /**
     * @generated from protobuf enum value: SPECIAL = 10;
     */
    SPECIAL = 10
}
declare class RelateCard$Type extends MessageType<RelateCard> {
    constructor();
    create(value?: PartialMessage<RelateCard>): RelateCard;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RelateCard): RelateCard;
    internalBinaryWrite(message: RelateCard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message viewunite.v1.RelateCard
 */
export declare const RelateCard: RelateCard$Type;
declare class Relates$Type extends MessageType<Relates> {
    constructor();
    create(value?: PartialMessage<Relates>): Relates;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Relates): Relates;
    internalBinaryWrite(message: Relates, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message viewunite.v1.Relates
 */
export declare const Relates: Relates$Type;
declare class CommonModule$Type extends MessageType<CommonModule> {
    constructor();
    create(value?: PartialMessage<CommonModule>): CommonModule;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CommonModule): CommonModule;
    internalBinaryWrite(message: CommonModule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message viewunite.v1.CommonModule
 */
export declare const CommonModule: CommonModule$Type;
declare class IntroductionTab$Type extends MessageType<IntroductionTab> {
    constructor();
    create(value?: PartialMessage<IntroductionTab>): IntroductionTab;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IntroductionTab): IntroductionTab;
    internalBinaryWrite(message: IntroductionTab, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message viewunite.v1.IntroductionTab
 */
export declare const IntroductionTab: IntroductionTab$Type;
declare class TabModule$Type extends MessageType<TabModule> {
    constructor();
    create(value?: PartialMessage<TabModule>): TabModule;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TabModule): TabModule;
    internalBinaryWrite(message: TabModule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message viewunite.v1.TabModule
 */
export declare const TabModule: TabModule$Type;
declare class Tab$Type extends MessageType<Tab> {
    constructor();
    create(value?: PartialMessage<Tab>): Tab;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Tab): Tab;
    internalBinaryWrite(message: Tab, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message viewunite.v1.Tab
 */
export declare const Tab: Tab$Type;
declare class CM$Type extends MessageType<CM> {
    constructor();
    create(value?: PartialMessage<CM>): CM;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CM): CM;
    internalBinaryWrite(message: CM, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message viewunite.v1.CM
 */
export declare const CM: CM$Type;
declare class ViewUniteReply$Type extends MessageType<ViewUniteReply> {
    constructor();
    create(value?: PartialMessage<ViewUniteReply>): ViewUniteReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewUniteReply): ViewUniteReply;
    internalBinaryWrite(message: ViewUniteReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message viewunite.v1.ViewUniteReply
 */
export declare const ViewUniteReply: ViewUniteReply$Type;
export {};
