// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/component/context.proto (package youtube.component, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.component.ResponseContext
 */
export declare class ResponseContext extends Message<ResponseContext> {
  /**
   * @generated from field: repeated youtube.component.ServiceTrackingParam serviceTrackingParams = 6;
   */
  serviceTrackingParams: ServiceTrackingParam[];

  constructor(data?: PartialMessage<ResponseContext>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.ResponseContext";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResponseContext;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResponseContext;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResponseContext;

  static equals(a: ResponseContext | PlainMessage<ResponseContext> | undefined, b: ResponseContext | PlainMessage<ResponseContext> | undefined): boolean;
}

/**
 * @generated from message youtube.component.ServiceTrackingParam
 */
export declare class ServiceTrackingParam extends Message<ServiceTrackingParam> {
  /**
   * @generated from field: int32 service = 1;
   */
  service: number;

  /**
   * @generated from field: repeated youtube.component.Param params = 2;
   */
  params: Param[];

  constructor(data?: PartialMessage<ServiceTrackingParam>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.ServiceTrackingParam";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceTrackingParam;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceTrackingParam;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceTrackingParam;

  static equals(a: ServiceTrackingParam | PlainMessage<ServiceTrackingParam> | undefined, b: ServiceTrackingParam | PlainMessage<ServiceTrackingParam> | undefined): boolean;
}

/**
 * @generated from message youtube.component.Param
 */
export declare class Param extends Message<Param> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;

  constructor(data?: PartialMessage<Param>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.Param";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Param;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Param;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Param;

  static equals(a: Param | PlainMessage<Param> | undefined, b: Param | PlainMessage<Param> | undefined): boolean;
}

