// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/component/context.proto (package youtube.component, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.component.ResponseContext
 */
export const ResponseContext = proto3.makeMessageType(
  "youtube.component.ResponseContext",
  () => [
    { no: 6, name: "serviceTrackingParams", kind: "message", T: ServiceTrackingParam, repeated: true },
  ],
);

/**
 * @generated from message youtube.component.ServiceTrackingParam
 */
export const ServiceTrackingParam = proto3.makeMessageType(
  "youtube.component.ServiceTrackingParam",
  () => [
    { no: 1, name: "service", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "params", kind: "message", T: Param, repeated: true },
  ],
);

/**
 * @generated from message youtube.component.Param
 */
export const Param = proto3.makeMessageType(
  "youtube.component.Param",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

