// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/component/framework.proto (package youtube.component, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.component.FrameworkUpdateTransport
 */
export declare class FrameworkUpdateTransport extends Message<FrameworkUpdateTransport> {
  /**
   * @generated from field: youtube.component.EntityBatchUpdate entityBatchUpdate = 1;
   */
  entityBatchUpdate?: EntityBatchUpdate;

  constructor(data?: PartialMessage<FrameworkUpdateTransport>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.FrameworkUpdateTransport";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FrameworkUpdateTransport;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FrameworkUpdateTransport;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FrameworkUpdateTransport;

  static equals(a: FrameworkUpdateTransport | PlainMessage<FrameworkUpdateTransport> | undefined, b: FrameworkUpdateTransport | PlainMessage<FrameworkUpdateTransport> | undefined): boolean;
}

/**
 * @generated from message youtube.component.EntityBatchUpdate
 */
export declare class EntityBatchUpdate extends Message<EntityBatchUpdate> {
  /**
   * @generated from field: repeated youtube.component.Mutation mutations = 1;
   */
  mutations: Mutation[];

  constructor(data?: PartialMessage<EntityBatchUpdate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.EntityBatchUpdate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EntityBatchUpdate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EntityBatchUpdate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EntityBatchUpdate;

  static equals(a: EntityBatchUpdate | PlainMessage<EntityBatchUpdate> | undefined, b: EntityBatchUpdate | PlainMessage<EntityBatchUpdate> | undefined): boolean;
}

/**
 * @generated from message youtube.component.Mutation
 */
export declare class Mutation extends Message<Mutation> {
  /**
   * @generated from field: string entityKey = 1;
   */
  entityKey: string;

  /**
   * @generated from field: int32 type = 2;
   */
  type: number;

  /**
   * @generated from field: youtube.component.Payload payload = 3;
   */
  payload?: Payload;

  constructor(data?: PartialMessage<Mutation>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.Mutation";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Mutation;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Mutation;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Mutation;

  static equals(a: Mutation | PlainMessage<Mutation> | undefined, b: Mutation | PlainMessage<Mutation> | undefined): boolean;
}

/**
 * @generated from message youtube.component.Payload
 */
export declare class Payload extends Message<Payload> {
  constructor(data?: PartialMessage<Payload>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.Payload";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Payload;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Payload;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Payload;

  static equals(a: Payload | PlainMessage<Payload> | undefined, b: Payload | PlainMessage<Payload> | undefined): boolean;
}

/**
 * @generated from message youtube.component.Entity
 */
export declare class Entity extends Message<Entity> {
  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 targetNo = 4;
   */
  targetNo: number;

  /**
   * @generated from field: int32 type = 5;
   */
  type: number;

  constructor(data?: PartialMessage<Entity>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.Entity";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Entity;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Entity;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Entity;

  static equals(a: Entity | PlainMessage<Entity> | undefined, b: Entity | PlainMessage<Entity> | undefined): boolean;
}

