// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/component/framework.proto (package youtube.component, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.component.FrameworkUpdateTransport
 */
export const FrameworkUpdateTransport = proto3.makeMessageType(
  "youtube.component.FrameworkUpdateTransport",
  () => [
    { no: 1, name: "entityBatchUpdate", kind: "message", T: EntityBatchUpdate },
  ],
);

/**
 * @generated from message youtube.component.EntityBatchUpdate
 */
export const EntityBatchUpdate = proto3.makeMessageType(
  "youtube.component.EntityBatchUpdate",
  () => [
    { no: 1, name: "mutations", kind: "message", T: Mutation, repeated: true },
  ],
);

/**
 * @generated from message youtube.component.Mutation
 */
export const Mutation = proto3.makeMessageType(
  "youtube.component.Mutation",
  () => [
    { no: 1, name: "entityKey", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "payload", kind: "message", T: Payload },
  ],
);

/**
 * @generated from message youtube.component.Payload
 */
export const Payload = proto3.makeMessageType(
  "youtube.component.Payload",
  [],
);

/**
 * @generated from message youtube.component.Entity
 */
export const Entity = proto3.makeMessageType(
  "youtube.component.Entity",
  () => [
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "targetNo", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "type", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

