// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/component/label.proto (package youtube.component, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.component.Label
 */
export declare class Label extends Message<Label> {
  /**
   * @generated from field: repeated youtube.component.Run runs = 1;
   */
  runs: Run[];

  constructor(data?: PartialMessage<Label>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.Label";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Label;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Label;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Label;

  static equals(a: Label | PlainMessage<Label> | undefined, b: Label | PlainMessage<Label> | undefined): boolean;
}

/**
 * @generated from message youtube.component.Run
 */
export declare class Run extends Message<Run> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<Run>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.component.Run";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Run;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Run;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Run;

  static equals(a: Run | PlainMessage<Run> | undefined, b: Run | PlainMessage<Run> | undefined): boolean;
}

