// @generated by protoc-gen-es v1.7.2
// @generated from file request.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message Request
 */
export const Request = proto3.makeMessageType(
  "Request",
  () => [
    { no: 1, name: "context", kind: "message", T: Context },
    { no: 2, name: "browseId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message Context
 */
export const Context = proto3.makeMessageType(
  "Context",
  () => [
    { no: 9, name: "adSignalsInfo", kind: "message", T: AdSignalsInfo },
  ],
);

/**
 * @generated from message AdSignalsInfo
 */
export const AdSignalsInfo = proto3.makeMessageType(
  "AdSignalsInfo",
  () => [
    { no: 1, name: "params", kind: "message", T: Params, repeated: true },
  ],
);

/**
 * @generated from message Params
 */
export const Params = proto3.makeMessageType(
  "Params",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

