// @generated by protoc-gen-es v1.7.2
// @generated from file response.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message Browse
 */
export declare class Browse extends Message<Browse> {
  /**
   * @generated from field: ResponseContext responseContext = 1;
   */
  responseContext?: ResponseContext;

  /**
   * @generated from field: n1F9 n1F9 = 9;
   */
  n1F9?: n1F9;

  /**
   * @generated from field: n1F10 n1F10 = 10;
   */
  n1F10?: n1F10;

  constructor(data?: PartialMessage<Browse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Browse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Browse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Browse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Browse;

  static equals(a: Browse | PlainMessage<Browse> | undefined, b: Browse | PlainMessage<Browse> | undefined): boolean;
}

/**
 * @generated from message ResponseContext
 */
export declare class ResponseContext extends Message<ResponseContext> {
  /**
   * @generated from field: repeated ServiceTrackingParams serviceTrackingParams = 6;
   */
  serviceTrackingParams: ServiceTrackingParams[];

  constructor(data?: PartialMessage<ResponseContext>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ResponseContext";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResponseContext;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResponseContext;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResponseContext;

  static equals(a: ResponseContext | PlainMessage<ResponseContext> | undefined, b: ResponseContext | PlainMessage<ResponseContext> | undefined): boolean;
}

/**
 * @generated from message ServiceTrackingParams
 */
export declare class ServiceTrackingParams extends Message<ServiceTrackingParams> {
  /**
   * @generated from field: int32 service = 1;
   */
  service: number;

  /**
   * @generated from field: repeated Params params = 2;
   */
  params: Params[];

  constructor(data?: PartialMessage<ServiceTrackingParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ServiceTrackingParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceTrackingParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceTrackingParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceTrackingParams;

  static equals(a: ServiceTrackingParams | PlainMessage<ServiceTrackingParams> | undefined, b: ServiceTrackingParams | PlainMessage<ServiceTrackingParams> | undefined): boolean;
}

/**
 * @generated from message Params
 */
export declare class Params extends Message<Params> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;

  constructor(data?: PartialMessage<Params>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Params";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params;

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean;
}

/**
 * @generated from message n1F9
 */
export declare class n1F9 extends Message<n1F9> {
  /**
   * @generated from field: m2F58173949 m2F58173949 = 58173949;
   */
  m2F58173949?: m2F58173949;

  /**
   * @generated from field: n6F153515154 n6F153515154 = 153515154;
   */
  n6F153515154?: n6F153515154;

  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<n1F9>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n1F9";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n1F9;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n1F9;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n1F9;

  static equals(a: n1F9 | PlainMessage<n1F9> | undefined, b: n1F9 | PlainMessage<n1F9> | undefined): boolean;
}

/**
 * @generated from message n1F10
 */
export declare class n1F10 extends Message<n1F10> {
  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<n1F10>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n1F10";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n1F10;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n1F10;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n1F10;

  static equals(a: n1F10 | PlainMessage<n1F10> | undefined, b: n1F10 | PlainMessage<n1F10> | undefined): boolean;
}

/**
 * @generated from message m2F58173949
 */
export declare class m2F58173949 extends Message<m2F58173949> {
  /**
   * @generated from field: repeated m3F1 m3F1 = 1;
   */
  m3F1: m3F1[];

  constructor(data?: PartialMessage<m2F58173949>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "m2F58173949";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): m2F58173949;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): m2F58173949;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): m2F58173949;

  static equals(a: m2F58173949 | PlainMessage<m2F58173949> | undefined, b: m2F58173949 | PlainMessage<m2F58173949> | undefined): boolean;
}

/**
 * @generated from message m3F1
 */
export declare class m3F1 extends Message<m3F1> {
  /**
   * @generated from field: m4F58174010 m4F58174010 = 58174010;
   */
  m4F58174010?: m4F58174010;

  constructor(data?: PartialMessage<m3F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "m3F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): m3F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): m3F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): m3F1;

  static equals(a: m3F1 | PlainMessage<m3F1> | undefined, b: m3F1 | PlainMessage<m3F1> | undefined): boolean;
}

/**
 * @generated from message m4F58174010
 */
export declare class m4F58174010 extends Message<m4F58174010> {
  /**
   * @generated from field: n1F10 n1F10 = 4;
   */
  n1F10?: n1F10;

  constructor(data?: PartialMessage<m4F58174010>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "m4F58174010";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): m4F58174010;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): m4F58174010;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): m4F58174010;

  static equals(a: m4F58174010 | PlainMessage<m4F58174010> | undefined, b: m4F58174010 | PlainMessage<m4F58174010> | undefined): boolean;
}

/**
 * @generated from message n2F49399797
 */
export declare class n2F49399797 extends Message<n2F49399797> {
  /**
   * @generated from field: repeated n3F1 n3F1 = 1;
   */
  n3F1: n3F1[];

  constructor(data?: PartialMessage<n2F49399797>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n2F49399797";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n2F49399797;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n2F49399797;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n2F49399797;

  static equals(a: n2F49399797 | PlainMessage<n2F49399797> | undefined, b: n2F49399797 | PlainMessage<n2F49399797> | undefined): boolean;
}

/**
 * @generated from message n3F1
 */
export declare class n3F1 extends Message<n3F1> {
  /**
   * @generated from field: n4F50195462 n4F50195462 = 50195462;
   */
  n4F50195462?: n4F50195462;

  /**
   * @generated from field: n4F51845067 n4F51845067 = 51845067;
   */
  n4F51845067?: n4F51845067;

  /**
   * @generated from field: n4F221496734 m4F221496734 = 221496734;
   */
  m4F221496734?: n4F221496734;

  constructor(data?: PartialMessage<n3F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n3F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n3F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n3F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n3F1;

  static equals(a: n3F1 | PlainMessage<n3F1> | undefined, b: n3F1 | PlainMessage<n3F1> | undefined): boolean;
}

/**
 * @generated from message n4F50195462
 */
export declare class n4F50195462 extends Message<n4F50195462> {
  /**
   * @generated from field: repeated n5F1 n5F1 = 1;
   */
  n5F1: n5F1[];

  constructor(data?: PartialMessage<n4F50195462>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n4F50195462";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n4F50195462;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n4F50195462;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n4F50195462;

  static equals(a: n4F50195462 | PlainMessage<n4F50195462> | undefined, b: n4F50195462 | PlainMessage<n4F50195462> | undefined): boolean;
}

/**
 * @generated from message n4F51845067
 */
export declare class n4F51845067 extends Message<n4F51845067> {
  /**
   * @generated from field: n5F5 n5F5 = 5;
   */
  n5F5?: n5F5;

  constructor(data?: PartialMessage<n4F51845067>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n4F51845067";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n4F51845067;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n4F51845067;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n4F51845067;

  static equals(a: n4F51845067 | PlainMessage<n4F51845067> | undefined, b: n4F51845067 | PlainMessage<n4F51845067> | undefined): boolean;
}

/**
 * @generated from message n4F221496734
 */
export declare class n4F221496734 extends Message<n4F221496734> {
  /**
   * @generated from field: n5F3 n5F3 = 3;
   */
  n5F3?: n5F3;

  /**
   * @generated from field: n5F10 n5F10 = 10;
   */
  n5F10?: n5F10;

  constructor(data?: PartialMessage<n4F221496734>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n4F221496734";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n4F221496734;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n4F221496734;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n4F221496734;

  static equals(a: n4F221496734 | PlainMessage<n4F221496734> | undefined, b: n4F221496734 | PlainMessage<n4F221496734> | undefined): boolean;
}

/**
 * @generated from message n5F1
 */
export declare class n5F1 extends Message<n5F1> {
  /**
   * @generated from field: n6F153515154 n6F153515154 = 153515154;
   */
  n6F153515154?: n6F153515154;

  constructor(data?: PartialMessage<n5F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n5F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n5F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n5F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n5F1;

  static equals(a: n5F1 | PlainMessage<n5F1> | undefined, b: n5F1 | PlainMessage<n5F1> | undefined): boolean;
}

/**
 * @generated from message n5F3
 */
export declare class n5F3 extends Message<n5F3> {
  /**
   * @generated from field: n6F1 n6F1 = 1;
   */
  n6F1?: n6F1;

  constructor(data?: PartialMessage<n5F3>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n5F3";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n5F3;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n5F3;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n5F3;

  static equals(a: n5F3 | PlainMessage<n5F3> | undefined, b: n5F3 | PlainMessage<n5F3> | undefined): boolean;
}

/**
 * @generated from message n5F5
 */
export declare class n5F5 extends Message<n5F5> {
  /**
   * @generated from field: n6F51431404 n6F51431404 = 51431404;
   */
  n6F51431404?: n6F51431404;

  constructor(data?: PartialMessage<n5F5>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n5F5";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n5F5;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n5F5;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n5F5;

  static equals(a: n5F5 | PlainMessage<n5F5> | undefined, b: n5F5 | PlainMessage<n5F5> | undefined): boolean;
}

/**
 * @generated from message n6F1
 */
export declare class n6F1 extends Message<n6F1> {
  /**
   * @generated from field: string staticLyric = 1;
   */
  staticLyric: string;

  constructor(data?: PartialMessage<n6F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n6F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n6F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n6F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n6F1;

  static equals(a: n6F1 | PlainMessage<n6F1> | undefined, b: n6F1 | PlainMessage<n6F1> | undefined): boolean;
}

/**
 * @generated from message n6F153515154
 */
export declare class n6F153515154 extends Message<n6F153515154> {
  /**
   * @generated from field: n7F172660663 n7F172660663 = 172660663;
   */
  n7F172660663?: n7F172660663;

  constructor(data?: PartialMessage<n6F153515154>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n6F153515154";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n6F153515154;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n6F153515154;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n6F153515154;

  static equals(a: n6F153515154 | PlainMessage<n6F153515154> | undefined, b: n6F153515154 | PlainMessage<n6F153515154> | undefined): boolean;
}

/**
 * @generated from message n6F51431404
 */
export declare class n6F51431404 extends Message<n6F51431404> {
  /**
   * @generated from field: repeated n5F1 n5F1 = 1;
   */
  n5F1: n5F1[];

  constructor(data?: PartialMessage<n6F51431404>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n6F51431404";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n6F51431404;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n6F51431404;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n6F51431404;

  static equals(a: n6F51431404 | PlainMessage<n6F51431404> | undefined, b: n6F51431404 | PlainMessage<n6F51431404> | undefined): boolean;
}

/**
 * @generated from message n7F172660663
 */
export declare class n7F172660663 extends Message<n7F172660663> {
  /**
   * @generated from field: n8F1 n8F1 = 1;
   */
  n8F1?: n8F1;

  /**
   * @generated from field: n8F2 n8F2 = 2;
   */
  n8F2?: n8F2;

  /**
   * @generated from field: n8F3 n8F3 = 3;
   */
  n8F3?: n8F3;

  constructor(data?: PartialMessage<n7F172660663>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n7F172660663";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n7F172660663;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n7F172660663;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n7F172660663;

  static equals(a: n7F172660663 | PlainMessage<n7F172660663> | undefined, b: n7F172660663 | PlainMessage<n7F172660663> | undefined): boolean;
}

/**
 * @generated from message n5F10
 */
export declare class n5F10 extends Message<n5F10> {
  /**
   * @generated from field: Origin origin = 1;
   */
  origin?: Origin;

  constructor(data?: PartialMessage<n5F10>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n5F10";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n5F10;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n5F10;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n5F10;

  static equals(a: n5F10 | PlainMessage<n5F10> | undefined, b: n5F10 | PlainMessage<n5F10> | undefined): boolean;
}

/**
 * @generated from message n8F1
 */
export declare class n8F1 extends Message<n8F1> {
  /**
   * @generated from field: n9F168777401 n9F168777401 = 168777401;
   */
  n9F168777401?: n9F168777401;

  constructor(data?: PartialMessage<n8F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n8F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n8F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n8F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n8F1;

  static equals(a: n8F1 | PlainMessage<n8F1> | undefined, b: n8F1 | PlainMessage<n8F1> | undefined): boolean;
}

/**
 * @generated from message n8F2
 */
export declare class n8F2 extends Message<n8F2> {
  /**
   * @generated from field: n9F183314536 n9F183314536 = 183314536;
   */
  n9F183314536?: n9F183314536;

  constructor(data?: PartialMessage<n8F2>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n8F2";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n8F2;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n8F2;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n8F2;

  static equals(a: n8F2 | PlainMessage<n8F2> | undefined, b: n8F2 | PlainMessage<n8F2> | undefined): boolean;
}

/**
 * @generated from message n8F3
 */
export declare class n8F3 extends Message<n8F3> {
  /**
   * @generated from field: n8F1 n8F1 = 1;
   */
  n8F1?: n8F1;

  /**
   * @generated from field: n8F2 n8F2 = 2;
   */
  n8F2?: n8F2;

  constructor(data?: PartialMessage<n8F3>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n8F3";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n8F3;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n8F3;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n8F3;

  static equals(a: n8F3 | PlainMessage<n8F3> | undefined, b: n8F3 | PlainMessage<n8F3> | undefined): boolean;
}

/**
 * @generated from message Origin
 */
export declare class Origin extends Message<Origin> {
  /**
   * @generated from field: string originText = 1;
   */
  originText: string;

  constructor(data?: PartialMessage<Origin>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Origin";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Origin;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Origin;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Origin;

  static equals(a: Origin | PlainMessage<Origin> | undefined, b: Origin | PlainMessage<Origin> | undefined): boolean;
}

/**
 * @generated from message n9F168777401
 */
export declare class n9F168777401 extends Message<n9F168777401> {
  /**
   * @generated from field: n10F3 n10F3 = 3;
   */
  n10F3?: n10F3;

  /**
   * @generated from field: n10F5 n10F5 = 5;
   */
  n10F5?: n10F5;

  constructor(data?: PartialMessage<n9F168777401>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n9F168777401";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n9F168777401;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n9F168777401;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n9F168777401;

  static equals(a: n9F168777401 | PlainMessage<n9F168777401> | undefined, b: n9F168777401 | PlainMessage<n9F168777401> | undefined): boolean;
}

/**
 * @generated from message n9F183314536
 */
export declare class n9F183314536 extends Message<n9F183314536> {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  constructor(data?: PartialMessage<n9F183314536>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n9F183314536";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n9F183314536;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n9F183314536;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n9F183314536;

  static equals(a: n9F183314536 | PlainMessage<n9F183314536> | undefined, b: n9F183314536 | PlainMessage<n9F183314536> | undefined): boolean;
}

/**
 * @generated from message n10F3
 */
export declare class n10F3 extends Message<n10F3> {
  /**
   * @generated from field: n11F172035250 n11F172035250 = 172035250;
   */
  n11F172035250?: n11F172035250;

  constructor(data?: PartialMessage<n10F3>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n10F3";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n10F3;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n10F3;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n10F3;

  static equals(a: n10F3 | PlainMessage<n10F3> | undefined, b: n10F3 | PlainMessage<n10F3> | undefined): boolean;
}

/**
 * @generated from message n10F5
 */
export declare class n10F5 extends Message<n10F5> {
  /**
   * @generated from field: n11F465160965 n11F465160965 = 465160965;
   */
  n11F465160965?: n11F465160965;

  constructor(data?: PartialMessage<n10F5>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n10F5";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n10F5;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n10F5;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n10F5;

  static equals(a: n10F5 | PlainMessage<n10F5> | undefined, b: n10F5 | PlainMessage<n10F5> | undefined): boolean;
}

/**
 * @generated from message n11F465160965
 */
export declare class n11F465160965 extends Message<n11F465160965> {
  /**
   * @generated from field: n12F4 n12F4 = 4;
   */
  n12F4?: n12F4;

  constructor(data?: PartialMessage<n11F465160965>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n11F465160965";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n11F465160965;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n11F465160965;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n11F465160965;

  static equals(a: n11F465160965 | PlainMessage<n11F465160965> | undefined, b: n11F465160965 | PlainMessage<n11F465160965> | undefined): boolean;
}

/**
 * @generated from message n12F4
 */
export declare class n12F4 extends Message<n12F4> {
  /**
   * @generated from field: repeated n13F1 n13F1 = 1;
   */
  n13F1: n13F1[];

  /**
   * @generated from field: string originText = 2;
   */
  originText: string;

  constructor(data?: PartialMessage<n12F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n12F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n12F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n12F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n12F4;

  static equals(a: n12F4 | PlainMessage<n12F4> | undefined, b: n12F4 | PlainMessage<n12F4> | undefined): boolean;
}

/**
 * @generated from message n13F1
 */
export declare class n13F1 extends Message<n13F1> {
  /**
   * @generated from field: string f1 = 1;
   */
  f1: string;

  constructor(data?: PartialMessage<n13F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n13F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n13F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n13F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n13F1;

  static equals(a: n13F1 | PlainMessage<n13F1> | undefined, b: n13F1 | PlainMessage<n13F1> | undefined): boolean;
}

/**
 * @generated from message n11F172035250
 */
export declare class n11F172035250 extends Message<n11F172035250> {
  /**
   * @generated from field: string type = 1;
   */
  type: string;

  constructor(data?: PartialMessage<n11F172035250>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "n11F172035250";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): n11F172035250;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): n11F172035250;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): n11F172035250;

  static equals(a: n11F172035250 | PlainMessage<n11F172035250> | undefined, b: n11F172035250 | PlainMessage<n11F172035250> | undefined): boolean;
}

/**
 * @generated from message Next
 */
export declare class Next extends Message<Next> {
  /**
   * @generated from field: a1F7 a1F7 = 7;
   */
  a1F7?: a1F7;

  /**
   * @generated from field: a1F8 a1F8 = 8;
   */
  a1F8?: a1F8;

  constructor(data?: PartialMessage<Next>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Next";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Next;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Next;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Next;

  static equals(a: Next | PlainMessage<Next> | undefined, b: Next | PlainMessage<Next> | undefined): boolean;
}

/**
 * @generated from message a1F7
 */
export declare class a1F7 extends Message<a1F7> {
  /**
   * @generated from field: a2F51779735 a2F51779735 = 51779735;
   */
  a2F51779735?: a2F51779735;

  /**
   * @generated from field: MusicPlayRender musicPlayRender = 125354411;
   */
  musicPlayRender?: MusicPlayRender;

  constructor(data?: PartialMessage<a1F7>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "a1F7";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): a1F7;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): a1F7;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): a1F7;

  static equals(a: a1F7 | PlainMessage<a1F7> | undefined, b: a1F7 | PlainMessage<a1F7> | undefined): boolean;
}

/**
 * @generated from message a1F8
 */
export declare class a1F8 extends Message<a1F8> {
  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<a1F8>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "a1F8";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): a1F8;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): a1F8;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): a1F8;

  static equals(a: a1F8 | PlainMessage<a1F8> | undefined, b: a1F8 | PlainMessage<a1F8> | undefined): boolean;
}

/**
 * @generated from message MusicPlayRender
 */
export declare class MusicPlayRender extends Message<MusicPlayRender> {
  /**
   * @generated from field: BottomRender bottomRender = 7;
   */
  bottomRender?: BottomRender;

  constructor(data?: PartialMessage<MusicPlayRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "MusicPlayRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MusicPlayRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MusicPlayRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MusicPlayRender;

  static equals(a: MusicPlayRender | PlainMessage<MusicPlayRender> | undefined, b: MusicPlayRender | PlainMessage<MusicPlayRender> | undefined): boolean;
}

/**
 * @generated from message BottomRender
 */
export declare class BottomRender extends Message<BottomRender> {
  /**
   * @generated from field: SectionTab sectionTab = 91700600;
   */
  sectionTab?: SectionTab;

  constructor(data?: PartialMessage<BottomRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "BottomRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BottomRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BottomRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BottomRender;

  static equals(a: BottomRender | PlainMessage<BottomRender> | undefined, b: BottomRender | PlainMessage<BottomRender> | undefined): boolean;
}

/**
 * @generated from message SectionTab
 */
export declare class SectionTab extends Message<SectionTab> {
  /**
   * @generated from field: repeated Item items = 1;
   */
  items: Item[];

  constructor(data?: PartialMessage<SectionTab>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SectionTab";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SectionTab;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SectionTab;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SectionTab;

  static equals(a: SectionTab | PlainMessage<SectionTab> | undefined, b: SectionTab | PlainMessage<SectionTab> | undefined): boolean;
}

/**
 * @generated from message Item
 */
export declare class Item extends Message<Item> {
  /**
   * @generated from field: Tab tab = 58174010;
   */
  tab?: Tab;

  constructor(data?: PartialMessage<Item>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Item";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Item;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Item;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Item;

  static equals(a: Item | PlainMessage<Item> | undefined, b: Item | PlainMessage<Item> | undefined): boolean;
}

/**
 * @generated from message Tab
 */
export declare class Tab extends Message<Tab> {
  /**
   * @generated from field: Info info = 1;
   */
  info?: Info;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  constructor(data?: PartialMessage<Tab>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Tab";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tab;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tab;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tab;

  static equals(a: Tab | PlainMessage<Tab> | undefined, b: Tab | PlainMessage<Tab> | undefined): boolean;
}

/**
 * @generated from message Info
 */
export declare class Info extends Message<Info> {
  /**
   * @generated from field: BrowseInfo BrowseInfo = 48687626;
   */
  BrowseInfo?: BrowseInfo;

  constructor(data?: PartialMessage<Info>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Info";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Info;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Info;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Info;

  static equals(a: Info | PlainMessage<Info> | undefined, b: Info | PlainMessage<Info> | undefined): boolean;
}

/**
 * @generated from message BrowseInfo
 */
export declare class BrowseInfo extends Message<BrowseInfo> {
  /**
   * @generated from field: string browseId = 2;
   */
  browseId: string;

  constructor(data?: PartialMessage<BrowseInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "BrowseInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BrowseInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BrowseInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BrowseInfo;

  static equals(a: BrowseInfo | PlainMessage<BrowseInfo> | undefined, b: BrowseInfo | PlainMessage<BrowseInfo> | undefined): boolean;
}

/**
 * @generated from message a2F51779735
 */
export declare class a2F51779735 extends Message<a2F51779735> {
  /**
   * @generated from field: a3F1 a3F1 = 1;
   */
  a3F1?: a3F1;

  constructor(data?: PartialMessage<a2F51779735>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "a2F51779735";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): a2F51779735;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): a2F51779735;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): a2F51779735;

  static equals(a: a2F51779735 | PlainMessage<a2F51779735> | undefined, b: a2F51779735 | PlainMessage<a2F51779735> | undefined): boolean;
}

/**
 * @generated from message a3F1
 */
export declare class a3F1 extends Message<a3F1> {
  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<a3F1>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "a3F1";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): a3F1;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): a3F1;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): a3F1;

  static equals(a: a3F1 | PlainMessage<a3F1> | undefined, b: a3F1 | PlainMessage<a3F1> | undefined): boolean;
}

/**
 * @generated from message Search
 */
export declare class Search extends Message<Search> {
  /**
   * @generated from field: s1F4 s1F4 = 4;
   */
  s1F4?: s1F4;

  /**
   * @generated from field: s1F7 s1F7 = 7;
   */
  s1F7?: s1F7;

  constructor(data?: PartialMessage<Search>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Search";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Search;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Search;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Search;

  static equals(a: Search | PlainMessage<Search> | undefined, b: Search | PlainMessage<Search> | undefined): boolean;
}

/**
 * @generated from message s1F4
 */
export declare class s1F4 extends Message<s1F4> {
  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<s1F4>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "s1F4";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): s1F4;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): s1F4;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): s1F4;

  static equals(a: s1F4 | PlainMessage<s1F4> | undefined, b: s1F4 | PlainMessage<s1F4> | undefined): boolean;
}

/**
 * @generated from message s1F7
 */
export declare class s1F7 extends Message<s1F7> {
  /**
   * @generated from field: n4F50195462 n4F50195462 = 50195462;
   */
  n4F50195462?: n4F50195462;

  /**
   * @generated from field: n2F49399797 n2F49399797 = 49399797;
   */
  n2F49399797?: n2F49399797;

  constructor(data?: PartialMessage<s1F7>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "s1F7";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): s1F7;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): s1F7;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): s1F7;

  static equals(a: s1F7 | PlainMessage<s1F7> | undefined, b: s1F7 | PlainMessage<s1F7> | undefined): boolean;
}

/**
 * @generated from message Shorts
 */
export declare class Shorts extends Message<Shorts> {
  /**
   * @generated from field: repeated Entry entries = 2;
   */
  entries: Entry[];

  constructor(data?: PartialMessage<Shorts>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Shorts";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Shorts;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Shorts;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Shorts;

  static equals(a: Shorts | PlainMessage<Shorts> | undefined, b: Shorts | PlainMessage<Shorts> | undefined): boolean;
}

/**
 * @generated from message Entry
 */
export declare class Entry extends Message<Entry> {
  /**
   * @generated from field: Command command = 1;
   */
  command?: Command;

  constructor(data?: PartialMessage<Entry>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Entry";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Entry;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Entry;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Entry;

  static equals(a: Entry | PlainMessage<Entry> | undefined, b: Entry | PlainMessage<Entry> | undefined): boolean;
}

/**
 * @generated from message Command
 */
export declare class Command extends Message<Command> {
  /**
   * @generated from field: ReelWatchEndpoint reelWatchEndpoint = 139608561;
   */
  reelWatchEndpoint?: ReelWatchEndpoint;

  constructor(data?: PartialMessage<Command>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Command";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Command;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Command;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Command;

  static equals(a: Command | PlainMessage<Command> | undefined, b: Command | PlainMessage<Command> | undefined): boolean;
}

/**
 * @generated from message ReelWatchEndpoint
 */
export declare class ReelWatchEndpoint extends Message<ReelWatchEndpoint> {
  /**
   * @generated from field: Overlay overlay = 8;
   */
  overlay?: Overlay;

  constructor(data?: PartialMessage<ReelWatchEndpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ReelWatchEndpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReelWatchEndpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReelWatchEndpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReelWatchEndpoint;

  static equals(a: ReelWatchEndpoint | PlainMessage<ReelWatchEndpoint> | undefined, b: ReelWatchEndpoint | PlainMessage<ReelWatchEndpoint> | undefined): boolean;
}

/**
 * @generated from message Overlay
 */
export declare class Overlay extends Message<Overlay> {
  /**
   * @generated from field: ReelPlayerOverlayRenderer reelPlayerOverlayRenderer = 139970731;
   */
  reelPlayerOverlayRenderer?: ReelPlayerOverlayRenderer;

  constructor(data?: PartialMessage<Overlay>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Overlay";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Overlay;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Overlay;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Overlay;

  static equals(a: Overlay | PlainMessage<Overlay> | undefined, b: Overlay | PlainMessage<Overlay> | undefined): boolean;
}

/**
 * @generated from message ReelPlayerOverlayRenderer
 */
export declare class ReelPlayerOverlayRenderer extends Message<ReelPlayerOverlayRenderer> {
  /**
   * @generated from field: int32 style = 12;
   */
  style: number;

  constructor(data?: PartialMessage<ReelPlayerOverlayRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ReelPlayerOverlayRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReelPlayerOverlayRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReelPlayerOverlayRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReelPlayerOverlayRenderer;

  static equals(a: ReelPlayerOverlayRenderer | PlainMessage<ReelPlayerOverlayRenderer> | undefined, b: ReelPlayerOverlayRenderer | PlainMessage<ReelPlayerOverlayRenderer> | undefined): boolean;
}

/**
 * @generated from message Guide
 */
export declare class Guide extends Message<Guide> {
  /**
   * @generated from field: repeated GuideItem guideItem4 = 4;
   */
  guideItem4: GuideItem[];

  /**
   * @generated from field: repeated GuideItem guideItem6 = 6;
   */
  guideItem6: GuideItem[];

  constructor(data?: PartialMessage<Guide>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Guide";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Guide;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Guide;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Guide;

  static equals(a: Guide | PlainMessage<Guide> | undefined, b: Guide | PlainMessage<Guide> | undefined): boolean;
}

/**
 * @generated from message GuideItem
 */
export declare class GuideItem extends Message<GuideItem> {
  /**
   * @generated from field: GuideSectionRenderer guideSectionRenderer = 117866661;
   */
  guideSectionRenderer?: GuideSectionRenderer;

  constructor(data?: PartialMessage<GuideItem>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "GuideItem";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GuideItem;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GuideItem;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GuideItem;

  static equals(a: GuideItem | PlainMessage<GuideItem> | undefined, b: GuideItem | PlainMessage<GuideItem> | undefined): boolean;
}

/**
 * @generated from message GuideSectionRenderer
 */
export declare class GuideSectionRenderer extends Message<GuideSectionRenderer> {
  /**
   * @generated from field: repeated RendererItem rendererItems = 1;
   */
  rendererItems: RendererItem[];

  constructor(data?: PartialMessage<GuideSectionRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "GuideSectionRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GuideSectionRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GuideSectionRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GuideSectionRenderer;

  static equals(a: GuideSectionRenderer | PlainMessage<GuideSectionRenderer> | undefined, b: GuideSectionRenderer | PlainMessage<GuideSectionRenderer> | undefined): boolean;
}

/**
 * @generated from message RendererItem
 */
export declare class RendererItem extends Message<RendererItem> {
  /**
   * @generated from field: guideEntryRenderer iconRender = 318370163;
   */
  iconRender?: guideEntryRenderer;

  /**
   * @generated from field: guideEntryRenderer labelRender = 117501096;
   */
  labelRender?: guideEntryRenderer;

  constructor(data?: PartialMessage<RendererItem>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "RendererItem";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RendererItem;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RendererItem;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RendererItem;

  static equals(a: RendererItem | PlainMessage<RendererItem> | undefined, b: RendererItem | PlainMessage<RendererItem> | undefined): boolean;
}

/**
 * @generated from message guideEntryRenderer
 */
export declare class guideEntryRenderer extends Message<guideEntryRenderer> {
  /**
   * @generated from field: string browseId = 1;
   */
  browseId: string;

  constructor(data?: PartialMessage<guideEntryRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "guideEntryRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): guideEntryRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): guideEntryRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): guideEntryRenderer;

  static equals(a: guideEntryRenderer | PlainMessage<guideEntryRenderer> | undefined, b: guideEntryRenderer | PlainMessage<guideEntryRenderer> | undefined): boolean;
}

/**
 * @generated from message Player
 */
export declare class Player extends Message<Player> {
  /**
   * @generated from field: repeated AdPlacement adPlacements = 7;
   */
  adPlacements: AdPlacement[];

  /**
   * @generated from field: PlayabilityStatus playabilityStatus = 2;
   */
  playabilityStatus?: PlayabilityStatus;

  /**
   * @generated from field: Captions captions = 10;
   */
  captions?: Captions;

  constructor(data?: PartialMessage<Player>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Player";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player;

  static equals(a: Player | PlainMessage<Player> | undefined, b: Player | PlainMessage<Player> | undefined): boolean;
}

/**
 * @generated from message AdPlacement
 */
export declare class AdPlacement extends Message<AdPlacement> {
  /**
   * @generated from field: AdPlacementRenderer adPlacementRenderer = 84813246;
   */
  adPlacementRenderer?: AdPlacementRenderer;

  constructor(data?: PartialMessage<AdPlacement>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "AdPlacement";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdPlacement;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdPlacement;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdPlacement;

  static equals(a: AdPlacement | PlainMessage<AdPlacement> | undefined, b: AdPlacement | PlainMessage<AdPlacement> | undefined): boolean;
}

/**
 * @generated from message AdPlacementRenderer
 */
export declare class AdPlacementRenderer extends Message<AdPlacementRenderer> {
  /**
   * @generated from field: string params = 4;
   */
  params: string;

  constructor(data?: PartialMessage<AdPlacementRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "AdPlacementRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdPlacementRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdPlacementRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdPlacementRenderer;

  static equals(a: AdPlacementRenderer | PlainMessage<AdPlacementRenderer> | undefined, b: AdPlacementRenderer | PlainMessage<AdPlacementRenderer> | undefined): boolean;
}

/**
 * @generated from message PlayabilityStatus
 */
export declare class PlayabilityStatus extends Message<PlayabilityStatus> {
  /**
   * @generated from field: PIPAbility pipAbility = 21;
   */
  pipAbility?: PIPAbility;

  /**
   * @generated from field: BackgroundAbility backgroundAbility = 11;
   */
  backgroundAbility?: BackgroundAbility;

  constructor(data?: PartialMessage<PlayabilityStatus>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "PlayabilityStatus";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayabilityStatus;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayabilityStatus;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayabilityStatus;

  static equals(a: PlayabilityStatus | PlainMessage<PlayabilityStatus> | undefined, b: PlayabilityStatus | PlainMessage<PlayabilityStatus> | undefined): boolean;
}

/**
 * @generated from message PIPAbility
 */
export declare class PIPAbility extends Message<PIPAbility> {
  /**
   * @generated from field: PIPlayer piplayer = 151635310;
   */
  piplayer?: PIPlayer;

  constructor(data?: PartialMessage<PIPAbility>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "PIPAbility";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PIPAbility;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PIPAbility;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PIPAbility;

  static equals(a: PIPAbility | PlainMessage<PIPAbility> | undefined, b: PIPAbility | PlainMessage<PIPAbility> | undefined): boolean;
}

/**
 * @generated from message BackgroundAbility
 */
export declare class BackgroundAbility extends Message<BackgroundAbility> {
  /**
   * @generated from field: BackgroundPlayer backgroundPlayer = 64657230;
   */
  backgroundPlayer?: BackgroundPlayer;

  constructor(data?: PartialMessage<BackgroundAbility>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "BackgroundAbility";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundAbility;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundAbility;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundAbility;

  static equals(a: BackgroundAbility | PlainMessage<BackgroundAbility> | undefined, b: BackgroundAbility | PlainMessage<BackgroundAbility> | undefined): boolean;
}

/**
 * @generated from message PIPlayer
 */
export declare class PIPlayer extends Message<PIPlayer> {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;

  constructor(data?: PartialMessage<PIPlayer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "PIPlayer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PIPlayer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PIPlayer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PIPlayer;

  static equals(a: PIPlayer | PlainMessage<PIPlayer> | undefined, b: PIPlayer | PlainMessage<PIPlayer> | undefined): boolean;
}

/**
 * @generated from message BackgroundPlayer
 */
export declare class BackgroundPlayer extends Message<BackgroundPlayer> {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;

  constructor(data?: PartialMessage<BackgroundPlayer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "BackgroundPlayer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundPlayer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundPlayer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundPlayer;

  static equals(a: BackgroundPlayer | PlainMessage<BackgroundPlayer> | undefined, b: BackgroundPlayer | PlainMessage<BackgroundPlayer> | undefined): boolean;
}

/**
 * @generated from message Captions
 */
export declare class Captions extends Message<Captions> {
  /**
   * @generated from field: PlayerCaptionsTracklistRenderer playerCaptionsTracklistRenderer = 51621377;
   */
  playerCaptionsTracklistRenderer?: PlayerCaptionsTracklistRenderer;

  constructor(data?: PartialMessage<Captions>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Captions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Captions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Captions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Captions;

  static equals(a: Captions | PlainMessage<Captions> | undefined, b: Captions | PlainMessage<Captions> | undefined): boolean;
}

/**
 * @generated from message PlayerCaptionsTracklistRenderer
 */
export declare class PlayerCaptionsTracklistRenderer extends Message<PlayerCaptionsTracklistRenderer> {
  /**
   * @generated from field: repeated CaptionTrack captionTracks = 1;
   */
  captionTracks: CaptionTrack[];

  /**
   * @generated from field: repeated AudioTrack audioTracks = 2;
   */
  audioTracks: AudioTrack[];

  /**
   * @generated from field: repeated TranslationLanguage translationLanguages = 3;
   */
  translationLanguages: TranslationLanguage[];

  /**
   * @generated from field: optional int32 defaultAudioTrackIndex = 4;
   */
  defaultAudioTrackIndex?: number;

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 6;
   */
  defaultCaptionTrackIndex?: number;

  constructor(data?: PartialMessage<PlayerCaptionsTracklistRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "PlayerCaptionsTracklistRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayerCaptionsTracklistRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayerCaptionsTracklistRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayerCaptionsTracklistRenderer;

  static equals(a: PlayerCaptionsTracklistRenderer | PlainMessage<PlayerCaptionsTracklistRenderer> | undefined, b: PlayerCaptionsTracklistRenderer | PlainMessage<PlayerCaptionsTracklistRenderer> | undefined): boolean;
}

/**
 * @generated from message CaptionTrack
 */
export declare class CaptionTrack extends Message<CaptionTrack> {
  /**
   * @generated from field: string baseUrl = 1;
   */
  baseUrl: string;

  /**
   * @generated from field: Name name = 2;
   */
  name?: Name;

  /**
   * @generated from field: string vssId = 3;
   */
  vssId: string;

  /**
   * @generated from field: string languageCode = 4;
   */
  languageCode: string;

  /**
   * @generated from field: optional string kind = 5;
   */
  kind?: string;

  /**
   * @generated from field: optional bool rtl = 6;
   */
  rtl?: boolean;

  /**
   * @generated from field: bool isTranslatable = 7;
   */
  isTranslatable: boolean;

  constructor(data?: PartialMessage<CaptionTrack>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "CaptionTrack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptionTrack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptionTrack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptionTrack;

  static equals(a: CaptionTrack | PlainMessage<CaptionTrack> | undefined, b: CaptionTrack | PlainMessage<CaptionTrack> | undefined): boolean;
}

/**
 * @generated from message AudioTrack
 */
export declare class AudioTrack extends Message<AudioTrack> {
  /**
   * @generated from field: repeated int32 captionTrackIndices = 2 [packed = false];
   */
  captionTrackIndices: number[];

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 3;
   */
  defaultCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 forcedCaptionTrackIndex = 4;
   */
  forcedCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 visibility = 5;
   */
  visibility?: number;

  /**
   * @generated from field: optional bool hasDefaultTrack = 6;
   */
  hasDefaultTrack?: boolean;

  /**
   * @generated from field: optional bool hasForcedTrack = 7;
   */
  hasForcedTrack?: boolean;

  /**
   * @generated from field: optional string audioTrackId = 8;
   */
  audioTrackId?: string;

  /**
   * @generated from field: optional int32 captionsInitialState = 11;
   */
  captionsInitialState?: number;

  constructor(data?: PartialMessage<AudioTrack>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "AudioTrack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AudioTrack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AudioTrack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AudioTrack;

  static equals(a: AudioTrack | PlainMessage<AudioTrack> | undefined, b: AudioTrack | PlainMessage<AudioTrack> | undefined): boolean;
}

/**
 * @generated from message TranslationLanguage
 */
export declare class TranslationLanguage extends Message<TranslationLanguage> {
  /**
   * @generated from field: string languageCode = 1;
   */
  languageCode: string;

  /**
   * @generated from field: Name languageName = 2;
   */
  languageName?: Name;

  constructor(data?: PartialMessage<TranslationLanguage>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "TranslationLanguage";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TranslationLanguage;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TranslationLanguage;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TranslationLanguage;

  static equals(a: TranslationLanguage | PlainMessage<TranslationLanguage> | undefined, b: TranslationLanguage | PlainMessage<TranslationLanguage> | undefined): boolean;
}

/**
 * @generated from message Name
 */
export declare class Name extends Message<Name> {
  /**
   * @generated from field: repeated Name.Runs runs = 1;
   */
  runs: Name_Runs[];

  constructor(data?: PartialMessage<Name>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Name";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Name;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Name;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Name;

  static equals(a: Name | PlainMessage<Name> | undefined, b: Name | PlainMessage<Name> | undefined): boolean;
}

/**
 * @generated from message Name.Runs
 */
export declare class Name_Runs extends Message<Name_Runs> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<Name_Runs>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Name.Runs";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Name_Runs;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Name_Runs;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Name_Runs;

  static equals(a: Name_Runs | PlainMessage<Name_Runs> | undefined, b: Name_Runs | PlainMessage<Name_Runs> | undefined): boolean;
}

/**
 * @generated from message Setting
 */
export declare class Setting extends Message<Setting> {
  /**
   * @generated from field: repeated SettingItem settingItems = 6;
   */
  settingItems: SettingItem[];

  /**
   *  St1F7 st1F7 = 7;
   *
   * @generated from field: TrackingParams trackingParams = 10;
   */
  trackingParams?: TrackingParams;

  constructor(data?: PartialMessage<Setting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Setting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Setting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Setting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Setting;

  static equals(a: Setting | PlainMessage<Setting> | undefined, b: Setting | PlainMessage<Setting> | undefined): boolean;
}

/**
 * @generated from message SettingItem
 */
export declare class SettingItem extends Message<SettingItem> {
  /**
   * @generated from field: SettingCategoryEntryRenderer settingCategoryEntryRenderer = 88478200;
   */
  settingCategoryEntryRenderer?: SettingCategoryEntryRenderer;

  /**
   * @generated from field: SettingCategoryCollectionRenderer settingCategoryCollectionRenderer = 66930374;
   */
  settingCategoryCollectionRenderer?: SettingCategoryCollectionRenderer;

  constructor(data?: PartialMessage<SettingItem>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SettingItem";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingItem;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingItem;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingItem;

  static equals(a: SettingItem | PlainMessage<SettingItem> | undefined, b: SettingItem | PlainMessage<SettingItem> | undefined): boolean;
}

/**
 * message  St1F7{
 *  SettingCategoryEntryRenderer settingCategoryEntryRenderer = 88478200;
 * }
 *
 * @generated from message TrackingParams
 */
export declare class TrackingParams extends Message<TrackingParams> {
  /**
   * @generated from field: int32 f1 = 1;
   */
  f1: number;

  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: int32 f3 = 3;
   */
  f3: number;

  /**
   * @generated from field: TimeInfo timeInfo = 4;
   */
  timeInfo?: TimeInfo;

  constructor(data?: PartialMessage<TrackingParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "TrackingParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TrackingParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TrackingParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TrackingParams;

  static equals(a: TrackingParams | PlainMessage<TrackingParams> | undefined, b: TrackingParams | PlainMessage<TrackingParams> | undefined): boolean;
}

/**
 * @generated from message TimeInfo
 */
export declare class TimeInfo extends Message<TimeInfo> {
  /**
   * @generated from field: uint64 timestamp = 1 [jstype = JS_STRING];
   */
  timestamp: string;

  /**
   * @generated from field: fixed32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: fixed32 f3 = 3;
   */
  f3: number;

  constructor(data?: PartialMessage<TimeInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "TimeInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimeInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimeInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimeInfo;

  static equals(a: TimeInfo | PlainMessage<TimeInfo> | undefined, b: TimeInfo | PlainMessage<TimeInfo> | undefined): boolean;
}

/**
 * @generated from message SettingCategoryEntryRenderer
 */
export declare class SettingCategoryEntryRenderer extends Message<SettingCategoryEntryRenderer> {
  /**
   * @generated from field: int32 f2 = 2;
   */
  f2: number;

  /**
   * @generated from field: int32 f3 = 3;
   */
  f3: number;

  /**
   * @generated from field: TrackingParams trackingParams = 5;
   */
  trackingParams?: TrackingParams;

  /**
   * @generated from field: int32 f6 = 6;
   */
  f6: number;

  /**
   * @generated from field: int32 f7 = 7;
   */
  f7: number;

  /**
   * @generated from field: int32 f8 = 8;
   */
  f8: number;

  /**
   * @generated from field: int32 f9 = 9;
   */
  f9: number;

  /**
   * @generated from field: int32 f10 = 10;
   */
  f10: number;

  /**
   * @generated from field: int32 f12 = 12;
   */
  f12: number;

  constructor(data?: PartialMessage<SettingCategoryEntryRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SettingCategoryEntryRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingCategoryEntryRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingCategoryEntryRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingCategoryEntryRenderer;

  static equals(a: SettingCategoryEntryRenderer | PlainMessage<SettingCategoryEntryRenderer> | undefined, b: SettingCategoryEntryRenderer | PlainMessage<SettingCategoryEntryRenderer> | undefined): boolean;
}

/**
 * @generated from message SettingCategoryCollectionRenderer
 */
export declare class SettingCategoryCollectionRenderer extends Message<SettingCategoryCollectionRenderer> {
  /**
   * @generated from field: repeated SubSetting subSettings = 3;
   */
  subSettings: SubSetting[];

  /**
   * @generated from field: int32 categoryId = 4;
   */
  categoryId: number;

  constructor(data?: PartialMessage<SettingCategoryCollectionRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SettingCategoryCollectionRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingCategoryCollectionRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingCategoryCollectionRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingCategoryCollectionRenderer;

  static equals(a: SettingCategoryCollectionRenderer | PlainMessage<SettingCategoryCollectionRenderer> | undefined, b: SettingCategoryCollectionRenderer | PlainMessage<SettingCategoryCollectionRenderer> | undefined): boolean;
}

/**
 * @generated from message SubSetting
 */
export declare class SubSetting extends Message<SubSetting> {
  /**
   * @generated from field: SettingBooleanRenderer settingBooleanRenderer = 61331416;
   */
  settingBooleanRenderer?: SettingBooleanRenderer;

  constructor(data?: PartialMessage<SubSetting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SubSetting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubSetting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubSetting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubSetting;

  static equals(a: SubSetting | PlainMessage<SubSetting> | undefined, b: SubSetting | PlainMessage<SubSetting> | undefined): boolean;
}

/**
 * @generated from message SettingBooleanRenderer
 */
export declare class SettingBooleanRenderer extends Message<SettingBooleanRenderer> {
  /**
   * @generated from field: ServiceEndpoint enableServiceEndpoint = 5;
   */
  enableServiceEndpoint?: ServiceEndpoint;

  /**
   * @generated from field: ServiceEndpoint disableServiceEndpoint = 6;
   */
  disableServiceEndpoint?: ServiceEndpoint;

  /**
   * @generated from field: TrackingParams clickTrackingParams = 13;
   */
  clickTrackingParams?: TrackingParams;

  /**
   * @generated from field: int32 itemId = 15;
   */
  itemId: number;

  constructor(data?: PartialMessage<SettingBooleanRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SettingBooleanRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingBooleanRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingBooleanRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingBooleanRenderer;

  static equals(a: SettingBooleanRenderer | PlainMessage<SettingBooleanRenderer> | undefined, b: SettingBooleanRenderer | PlainMessage<SettingBooleanRenderer> | undefined): boolean;
}

/**
 * @generated from message ServiceEndpoint
 */
export declare class ServiceEndpoint extends Message<ServiceEndpoint> {
  /**
   * @generated from field: TrackingParams trackingParams = 2;
   */
  trackingParams?: TrackingParams;

  /**
   * @generated from field: SetClientSettingEndpoint setClientSettingEndpoint = 81212182;
   */
  setClientSettingEndpoint?: SetClientSettingEndpoint;

  constructor(data?: PartialMessage<ServiceEndpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ServiceEndpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceEndpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceEndpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceEndpoint;

  static equals(a: ServiceEndpoint | PlainMessage<ServiceEndpoint> | undefined, b: ServiceEndpoint | PlainMessage<ServiceEndpoint> | undefined): boolean;
}

/**
 * @generated from message SetClientSettingEndpoint
 */
export declare class SetClientSettingEndpoint extends Message<SetClientSettingEndpoint> {
  /**
   * @generated from field: SettingDatas settingDatas = 1;
   */
  settingDatas?: SettingDatas;

  constructor(data?: PartialMessage<SetClientSettingEndpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SetClientSettingEndpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetClientSettingEndpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetClientSettingEndpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetClientSettingEndpoint;

  static equals(a: SetClientSettingEndpoint | PlainMessage<SetClientSettingEndpoint> | undefined, b: SetClientSettingEndpoint | PlainMessage<SetClientSettingEndpoint> | undefined): boolean;
}

/**
 * @generated from message SettingDatas
 */
export declare class SettingDatas extends Message<SettingDatas> {
  /**
   * @generated from field: ClientSettingEnum clientSettingEnum = 1;
   */
  clientSettingEnum?: ClientSettingEnum;

  /**
   * @generated from field: bool boolValue = 3;
   */
  boolValue: boolean;

  constructor(data?: PartialMessage<SettingDatas>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "SettingDatas";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingDatas;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingDatas;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingDatas;

  static equals(a: SettingDatas | PlainMessage<SettingDatas> | undefined, b: SettingDatas | PlainMessage<SettingDatas> | undefined): boolean;
}

/**
 * @generated from message ClientSettingEnum
 */
export declare class ClientSettingEnum extends Message<ClientSettingEnum> {
  /**
   * @generated from field: int32 item = 1;
   */
  item: number;

  constructor(data?: PartialMessage<ClientSettingEnum>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ClientSettingEnum";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClientSettingEnum;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClientSettingEnum;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClientSettingEnum;

  static equals(a: ClientSettingEnum | PlainMessage<ClientSettingEnum> | undefined, b: ClientSettingEnum | PlainMessage<ClientSettingEnum> | undefined): boolean;
}

