// @generated by protoc-gen-es v1.7.2
// @generated from file response/browse.proto (package youtube.response.browse, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { FrameworkUpdateTransport } from "./frameworkUpdate_pb.js";

/**
 * @generated from message youtube.response.browse.Browse
 */
export const Browse = proto3.makeMessageType(
  "youtube.response.browse.Browse",
  () => [
    { no: 1, name: "responseContext", kind: "message", T: ResponseContext },
    { no: 9, name: "contents", kind: "message", T: Contents },
    { no: 10, name: "onResponseReceivedActions", kind: "message", T: Contents },
    { no: 777, name: "frameworkUpdateTransport", kind: "message", T: FrameworkUpdateTransport },
  ],
);

/**
 * @generated from message youtube.response.browse.ResponseContext
 */
export const ResponseContext = proto3.makeMessageType(
  "youtube.response.browse.ResponseContext",
  () => [
    { no: 6, name: "serviceTrackingParams", kind: "message", T: ServiceTrackingParams, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.browse.ServiceTrackingParams
 */
export const ServiceTrackingParams = proto3.makeMessageType(
  "youtube.response.browse.ServiceTrackingParams",
  () => [
    { no: 1, name: "service", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "params", kind: "message", T: Params, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.browse.Params
 */
export const Params = proto3.makeMessageType(
  "youtube.response.browse.Params",
  () => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message youtube.response.browse.Contents
 */
export const Contents = proto3.makeMessageType(
  "youtube.response.browse.Contents",
  () => [
    { no: 58173949, name: "browseResultsRenderer", kind: "message", T: BrowseResultsRenderer },
    { no: 153515154, name: "videoWithContextRenderer", kind: "message", T: VideoWithContextRenderer },
    { no: 49399797, name: "richGridRenderer", kind: "message", T: RichGridRenderer },
  ],
);

/**
 * @generated from message youtube.response.browse.BrowseResultsRenderer
 */
export const BrowseResultsRenderer = proto3.makeMessageType(
  "youtube.response.browse.BrowseResultsRenderer",
  () => [
    { no: 1, name: "tabs", kind: "message", T: Tab, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.browse.Tab
 */
export const Tab = proto3.makeMessageType(
  "youtube.response.browse.Tab",
  () => [
    { no: 58174010, name: "tabRenderer", kind: "message", T: TabRenderer },
  ],
);

/**
 * @generated from message youtube.response.browse.TabRenderer
 */
export const TabRenderer = proto3.makeMessageType(
  "youtube.response.browse.TabRenderer",
  () => [
    { no: 4, name: "contents", kind: "message", T: Contents },
  ],
);

/**
 * @generated from message youtube.response.browse.RichGridRenderer
 */
export const RichGridRenderer = proto3.makeMessageType(
  "youtube.response.browse.RichGridRenderer",
  () => [
    { no: 1, name: "richGridContents", kind: "message", T: RichGridContent, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.browse.RichGridContent
 */
export const RichGridContent = proto3.makeMessageType(
  "youtube.response.browse.RichGridContent",
  () => [
    { no: 50195462, name: "richItemRenderer", kind: "message", T: RichItemRenderer },
    { no: 51845067, name: "richSectionRenderer", kind: "message", T: RichSectionRenderer },
    { no: 221496734, name: "musicDescriptionShelfRenderer", kind: "message", T: MusicDescriptionShelfRenderer },
  ],
);

/**
 * @generated from message youtube.response.browse.RichItemRenderer
 */
export const RichItemRenderer = proto3.makeMessageType(
  "youtube.response.browse.RichItemRenderer",
  () => [
    { no: 1, name: "richItemContent", kind: "message", T: RichItemContent, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.browse.RichItemContent
 */
export const RichItemContent = proto3.makeMessageType(
  "youtube.response.browse.RichItemContent",
  () => [
    { no: 153515154, name: "videoWithContextRenderer", kind: "message", T: VideoWithContextRenderer },
  ],
);

/**
 * @generated from message youtube.response.browse.VideoWithContextRenderer
 */
export const VideoWithContextRenderer = proto3.makeMessageType(
  "youtube.response.browse.VideoWithContextRenderer",
  () => [
    { no: 172660663, name: "videoRendererContent", kind: "message", T: VideoRendererContent },
  ],
);

/**
 * @generated from message youtube.response.browse.VideoRendererContent
 */
export const VideoRendererContent = proto3.makeMessageType(
  "youtube.response.browse.VideoRendererContent",
  () => [
    { no: 1, name: "videoInfo", kind: "message", T: VideoInfo },
    { no: 2, name: "renderInfo", kind: "message", T: RenderInfo },
  ],
);

/**
 * @generated from message youtube.response.browse.VideoInfo
 */
export const VideoInfo = proto3.makeMessageType(
  "youtube.response.browse.VideoInfo",
  () => [
    { no: 168777401, name: "videoContext", kind: "message", T: VideoContext },
  ],
);

/**
 * @generated from message youtube.response.browse.VideoContext
 */
export const VideoContext = proto3.makeMessageType(
  "youtube.response.browse.VideoContext",
  () => [
    { no: 5, name: "videoContent", kind: "message", T: VideoContent },
  ],
);

/**
 * @generated from message youtube.response.browse.VideoContent
 */
export const VideoContent = proto3.makeMessageType(
  "youtube.response.browse.VideoContent",
  () => [
    { no: 465160965, name: "timedLyricsRender", kind: "message", T: TimedLyricsRender },
  ],
);

/**
 * @generated from message youtube.response.browse.TimedLyricsRender
 */
export const TimedLyricsRender = proto3.makeMessageType(
  "youtube.response.browse.TimedLyricsRender",
  () => [
    { no: 4, name: "timedLyricsContent", kind: "message", T: TimedLyricsContent },
  ],
);

/**
 * @generated from message youtube.response.browse.TimedLyricsContent
 */
export const TimedLyricsContent = proto3.makeMessageType(
  "youtube.response.browse.TimedLyricsContent",
  () => [
    { no: 1, name: "runs", kind: "message", T: Run, repeated: true },
    { no: 2, name: "footerLabel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message youtube.response.browse.RenderInfo
 */
export const RenderInfo = proto3.makeMessageType(
  "youtube.response.browse.RenderInfo",
  () => [
    { no: 183314536, name: "layoutRender", kind: "message", T: LayoutRender },
  ],
);

/**
 * @generated from message youtube.response.browse.LayoutRender
 */
export const LayoutRender = proto3.makeMessageType(
  "youtube.response.browse.LayoutRender",
  () => [
    { no: 1, name: "eml", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message youtube.response.browse.RichSectionRenderer
 */
export const RichSectionRenderer = proto3.makeMessageType(
  "youtube.response.browse.RichSectionRenderer",
  () => [
    { no: 5, name: "richSectionContent", kind: "message", T: RichSectionContent },
  ],
);

/**
 * @generated from message youtube.response.browse.RichSectionContent
 */
export const RichSectionContent = proto3.makeMessageType(
  "youtube.response.browse.RichSectionContent",
  () => [
    { no: 51431404, name: "reelShelfRenderer", kind: "message", T: ReelShelfRenderer },
  ],
);

/**
 * @generated from message youtube.response.browse.ReelShelfRenderer
 */
export const ReelShelfRenderer = proto3.makeMessageType(
  "youtube.response.browse.ReelShelfRenderer",
  () => [
    { no: 1, name: "richItemContent", kind: "message", T: RichItemContent, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.browse.MusicDescriptionShelfRenderer
 */
export const MusicDescriptionShelfRenderer = proto3.makeMessageType(
  "youtube.response.browse.MusicDescriptionShelfRenderer",
  () => [
    { no: 3, name: "description", kind: "message", T: Label },
    { no: 10, name: "footer", kind: "message", T: Label },
  ],
);

/**
 * @generated from message youtube.response.browse.Label
 */
export const Label = proto3.makeMessageType(
  "youtube.response.browse.Label",
  () => [
    { no: 1, name: "runs", kind: "message", T: Run, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.browse.Run
 */
export const Run = proto3.makeMessageType(
  "youtube.response.browse.Run",
  () => [
    { no: 1, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

