// @generated by protoc-gen-es v1.7.2
// @generated from file response/browse.proto (package youtube.response.browse, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.browse.Browse
 */
export declare class Browse extends Message<Browse> {
  /**
   * @generated from field: youtube.response.browse.ResponseContext responseContext = 1;
   */
  responseContext?: ResponseContext;

  /**
   * @generated from field: youtube.response.browse.Contents contents = 9;
   */
  contents?: Contents;

  /**
   * @generated from field: youtube.response.browse.Contents onResponseReceivedActions = 10;
   */
  onResponseReceivedActions?: Contents;

  constructor(data?: PartialMessage<Browse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Browse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Browse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Browse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Browse;

  static equals(a: Browse | PlainMessage<Browse> | undefined, b: Browse | PlainMessage<Browse> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.ResponseContext
 */
export declare class ResponseContext extends Message<ResponseContext> {
  /**
   * @generated from field: repeated youtube.response.browse.ServiceTrackingParams serviceTrackingParams = 6;
   */
  serviceTrackingParams: ServiceTrackingParams[];

  constructor(data?: PartialMessage<ResponseContext>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.ResponseContext";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResponseContext;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResponseContext;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResponseContext;

  static equals(a: ResponseContext | PlainMessage<ResponseContext> | undefined, b: ResponseContext | PlainMessage<ResponseContext> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.ServiceTrackingParams
 */
export declare class ServiceTrackingParams extends Message<ServiceTrackingParams> {
  /**
   * @generated from field: int32 service = 1;
   */
  service: number;

  /**
   * @generated from field: repeated youtube.response.browse.Params params = 2;
   */
  params: Params[];

  constructor(data?: PartialMessage<ServiceTrackingParams>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.ServiceTrackingParams";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceTrackingParams;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceTrackingParams;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceTrackingParams;

  static equals(a: ServiceTrackingParams | PlainMessage<ServiceTrackingParams> | undefined, b: ServiceTrackingParams | PlainMessage<ServiceTrackingParams> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.Params
 */
export declare class Params extends Message<Params> {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;

  constructor(data?: PartialMessage<Params>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Params";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params;

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.Contents
 */
export declare class Contents extends Message<Contents> {
  /**
   * @generated from field: youtube.response.browse.BrowseResultsRenderer browseResultsRenderer = 58173949;
   */
  browseResultsRenderer?: BrowseResultsRenderer;

  /**
   * @generated from field: youtube.response.browse.VideoWithContextRenderer videoWithContextRenderer = 153515154;
   */
  videoWithContextRenderer?: VideoWithContextRenderer;

  /**
   * @generated from field: youtube.response.browse.RichGridRenderer richGridRenderer = 49399797;
   */
  richGridRenderer?: RichGridRenderer;

  constructor(data?: PartialMessage<Contents>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Contents";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Contents;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Contents;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Contents;

  static equals(a: Contents | PlainMessage<Contents> | undefined, b: Contents | PlainMessage<Contents> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.BrowseResultsRenderer
 */
export declare class BrowseResultsRenderer extends Message<BrowseResultsRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.Tab tabs = 1;
   */
  tabs: Tab[];

  constructor(data?: PartialMessage<BrowseResultsRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.BrowseResultsRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BrowseResultsRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BrowseResultsRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BrowseResultsRenderer;

  static equals(a: BrowseResultsRenderer | PlainMessage<BrowseResultsRenderer> | undefined, b: BrowseResultsRenderer | PlainMessage<BrowseResultsRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.Tab
 */
export declare class Tab extends Message<Tab> {
  /**
   * @generated from field: youtube.response.browse.TabRenderer tabRenderer = 58174010;
   */
  tabRenderer?: TabRenderer;

  constructor(data?: PartialMessage<Tab>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Tab";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tab;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tab;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tab;

  static equals(a: Tab | PlainMessage<Tab> | undefined, b: Tab | PlainMessage<Tab> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.TabRenderer
 */
export declare class TabRenderer extends Message<TabRenderer> {
  /**
   * @generated from field: youtube.response.browse.Contents contents = 4;
   */
  contents?: Contents;

  constructor(data?: PartialMessage<TabRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.TabRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TabRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TabRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TabRenderer;

  static equals(a: TabRenderer | PlainMessage<TabRenderer> | undefined, b: TabRenderer | PlainMessage<TabRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RichGridRenderer
 */
export declare class RichGridRenderer extends Message<RichGridRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.RichGridContent richGridContents = 1;
   */
  richGridContents: RichGridContent[];

  constructor(data?: PartialMessage<RichGridRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RichGridRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RichGridRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RichGridRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RichGridRenderer;

  static equals(a: RichGridRenderer | PlainMessage<RichGridRenderer> | undefined, b: RichGridRenderer | PlainMessage<RichGridRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RichGridContent
 */
export declare class RichGridContent extends Message<RichGridContent> {
  /**
   * @generated from field: youtube.response.browse.RichItemRenderer richItemRenderer = 50195462;
   */
  richItemRenderer?: RichItemRenderer;

  /**
   * @generated from field: youtube.response.browse.RichSectionRenderer richSectionRenderer = 51845067;
   */
  richSectionRenderer?: RichSectionRenderer;

  /**
   * @generated from field: youtube.response.browse.MusicDescriptionShelfRenderer musicDescriptionShelfRenderer = 221496734;
   */
  musicDescriptionShelfRenderer?: MusicDescriptionShelfRenderer;

  constructor(data?: PartialMessage<RichGridContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RichGridContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RichGridContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RichGridContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RichGridContent;

  static equals(a: RichGridContent | PlainMessage<RichGridContent> | undefined, b: RichGridContent | PlainMessage<RichGridContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RichItemRenderer
 */
export declare class RichItemRenderer extends Message<RichItemRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.RichItemContent richItemContent = 1;
   */
  richItemContent: RichItemContent[];

  constructor(data?: PartialMessage<RichItemRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RichItemRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RichItemRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RichItemRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RichItemRenderer;

  static equals(a: RichItemRenderer | PlainMessage<RichItemRenderer> | undefined, b: RichItemRenderer | PlainMessage<RichItemRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RichItemContent
 */
export declare class RichItemContent extends Message<RichItemContent> {
  /**
   * @generated from field: youtube.response.browse.VideoWithContextRenderer videoWithContextRenderer = 153515154;
   */
  videoWithContextRenderer?: VideoWithContextRenderer;

  constructor(data?: PartialMessage<RichItemContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RichItemContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RichItemContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RichItemContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RichItemContent;

  static equals(a: RichItemContent | PlainMessage<RichItemContent> | undefined, b: RichItemContent | PlainMessage<RichItemContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoWithContextRenderer
 */
export declare class VideoWithContextRenderer extends Message<VideoWithContextRenderer> {
  /**
   * @generated from field: youtube.response.browse.VideoRendererContent videoRendererContent = 172660663;
   */
  videoRendererContent?: VideoRendererContent;

  constructor(data?: PartialMessage<VideoWithContextRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoWithContextRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoWithContextRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoWithContextRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoWithContextRenderer;

  static equals(a: VideoWithContextRenderer | PlainMessage<VideoWithContextRenderer> | undefined, b: VideoWithContextRenderer | PlainMessage<VideoWithContextRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoRendererContent
 */
export declare class VideoRendererContent extends Message<VideoRendererContent> {
  /**
   * @generated from field: youtube.response.browse.VideoInfo videoInfo = 1;
   */
  videoInfo?: VideoInfo;

  /**
   * @generated from field: youtube.response.browse.RenderInfo renderInfo = 2;
   */
  renderInfo?: RenderInfo;

  constructor(data?: PartialMessage<VideoRendererContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoRendererContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoRendererContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoRendererContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoRendererContent;

  static equals(a: VideoRendererContent | PlainMessage<VideoRendererContent> | undefined, b: VideoRendererContent | PlainMessage<VideoRendererContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoInfo
 */
export declare class VideoInfo extends Message<VideoInfo> {
  /**
   * @generated from field: youtube.response.browse.VideoContext videoContext = 168777401;
   */
  videoContext?: VideoContext;

  constructor(data?: PartialMessage<VideoInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoInfo;

  static equals(a: VideoInfo | PlainMessage<VideoInfo> | undefined, b: VideoInfo | PlainMessage<VideoInfo> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoContext
 */
export declare class VideoContext extends Message<VideoContext> {
  /**
   * @generated from field: youtube.response.browse.VideoContent videoContent = 5;
   */
  videoContent?: VideoContent;

  constructor(data?: PartialMessage<VideoContext>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoContext";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoContext;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoContext;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoContext;

  static equals(a: VideoContext | PlainMessage<VideoContext> | undefined, b: VideoContext | PlainMessage<VideoContext> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoContent
 */
export declare class VideoContent extends Message<VideoContent> {
  /**
   * @generated from field: youtube.response.browse.TimedLyricsRender timedLyricsRender = 465160965;
   */
  timedLyricsRender?: TimedLyricsRender;

  constructor(data?: PartialMessage<VideoContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoContent;

  static equals(a: VideoContent | PlainMessage<VideoContent> | undefined, b: VideoContent | PlainMessage<VideoContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.TimedLyricsRender
 */
export declare class TimedLyricsRender extends Message<TimedLyricsRender> {
  /**
   * @generated from field: youtube.response.browse.TimedLyricsContent timedLyricsContent = 4;
   */
  timedLyricsContent?: TimedLyricsContent;

  constructor(data?: PartialMessage<TimedLyricsRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.TimedLyricsRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimedLyricsRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimedLyricsRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimedLyricsRender;

  static equals(a: TimedLyricsRender | PlainMessage<TimedLyricsRender> | undefined, b: TimedLyricsRender | PlainMessage<TimedLyricsRender> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.TimedLyricsContent
 */
export declare class TimedLyricsContent extends Message<TimedLyricsContent> {
  /**
   * @generated from field: repeated youtube.response.browse.Run runs = 1;
   */
  runs: Run[];

  /**
   * @generated from field: string footerLabel = 2;
   */
  footerLabel: string;

  constructor(data?: PartialMessage<TimedLyricsContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.TimedLyricsContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimedLyricsContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimedLyricsContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimedLyricsContent;

  static equals(a: TimedLyricsContent | PlainMessage<TimedLyricsContent> | undefined, b: TimedLyricsContent | PlainMessage<TimedLyricsContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RenderInfo
 */
export declare class RenderInfo extends Message<RenderInfo> {
  /**
   * @generated from field: youtube.response.browse.LayoutRender layoutRender = 183314536;
   */
  layoutRender?: LayoutRender;

  constructor(data?: PartialMessage<RenderInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RenderInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenderInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenderInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenderInfo;

  static equals(a: RenderInfo | PlainMessage<RenderInfo> | undefined, b: RenderInfo | PlainMessage<RenderInfo> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.LayoutRender
 */
export declare class LayoutRender extends Message<LayoutRender> {
  /**
   * @generated from field: string eml = 1;
   */
  eml: string;

  constructor(data?: PartialMessage<LayoutRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.LayoutRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LayoutRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LayoutRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LayoutRender;

  static equals(a: LayoutRender | PlainMessage<LayoutRender> | undefined, b: LayoutRender | PlainMessage<LayoutRender> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RichSectionRenderer
 */
export declare class RichSectionRenderer extends Message<RichSectionRenderer> {
  /**
   * @generated from field: youtube.response.browse.RichSectionContent richSectionContent = 5;
   */
  richSectionContent?: RichSectionContent;

  constructor(data?: PartialMessage<RichSectionRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RichSectionRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RichSectionRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RichSectionRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RichSectionRenderer;

  static equals(a: RichSectionRenderer | PlainMessage<RichSectionRenderer> | undefined, b: RichSectionRenderer | PlainMessage<RichSectionRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RichSectionContent
 */
export declare class RichSectionContent extends Message<RichSectionContent> {
  /**
   * @generated from field: youtube.response.browse.ReelShelfRenderer reelShelfRenderer = 51431404;
   */
  reelShelfRenderer?: ReelShelfRenderer;

  constructor(data?: PartialMessage<RichSectionContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RichSectionContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RichSectionContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RichSectionContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RichSectionContent;

  static equals(a: RichSectionContent | PlainMessage<RichSectionContent> | undefined, b: RichSectionContent | PlainMessage<RichSectionContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.ReelShelfRenderer
 */
export declare class ReelShelfRenderer extends Message<ReelShelfRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.RichItemContent richItemContent = 1;
   */
  richItemContent: RichItemContent[];

  constructor(data?: PartialMessage<ReelShelfRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.ReelShelfRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReelShelfRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReelShelfRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReelShelfRenderer;

  static equals(a: ReelShelfRenderer | PlainMessage<ReelShelfRenderer> | undefined, b: ReelShelfRenderer | PlainMessage<ReelShelfRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.MusicDescriptionShelfRenderer
 */
export declare class MusicDescriptionShelfRenderer extends Message<MusicDescriptionShelfRenderer> {
  /**
   * @generated from field: youtube.response.browse.Label description = 3;
   */
  description?: Label;

  /**
   * @generated from field: youtube.response.browse.Label footer = 10;
   */
  footer?: Label;

  constructor(data?: PartialMessage<MusicDescriptionShelfRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.MusicDescriptionShelfRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MusicDescriptionShelfRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MusicDescriptionShelfRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MusicDescriptionShelfRenderer;

  static equals(a: MusicDescriptionShelfRenderer | PlainMessage<MusicDescriptionShelfRenderer> | undefined, b: MusicDescriptionShelfRenderer | PlainMessage<MusicDescriptionShelfRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.Label
 */
export declare class Label extends Message<Label> {
  /**
   * @generated from field: repeated youtube.response.browse.Run runs = 1;
   */
  runs: Run[];

  constructor(data?: PartialMessage<Label>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Label";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Label;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Label;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Label;

  static equals(a: Label | PlainMessage<Label> | undefined, b: Label | PlainMessage<Label> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.Run
 */
export declare class Run extends Message<Run> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<Run>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Run";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Run;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Run;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Run;

  static equals(a: Run | PlainMessage<Run> | undefined, b: Run | PlainMessage<Run> | undefined): boolean;
}

