// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/browse.proto (package youtube.response.browse, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { ResponseContext } from "../component/context_pb.js";
import type { FrameworkUpdateTransport } from "../component/framework_pb.js";
import type { Label, Run } from "../component/label_pb.js";

/**
 * @generated from message youtube.response.browse.Browse
 */
export declare class Browse extends Message<Browse> {
  /**
   * @generated from field: youtube.component.ResponseContext responseContext = 1;
   */
  responseContext?: ResponseContext;

  /**
   * @generated from field: youtube.response.browse.Content content = 9;
   */
  content?: Content;

  /**
   * @generated from field: youtube.response.browse.Content onResponseReceivedAction = 10;
   */
  onResponseReceivedAction?: Content;

  /**
   * @generated from field: youtube.component.FrameworkUpdateTransport frameworkUpdateTransport = 777;
   */
  frameworkUpdateTransport?: FrameworkUpdateTransport;

  constructor(data?: PartialMessage<Browse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Browse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Browse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Browse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Browse;

  static equals(a: Browse | PlainMessage<Browse> | undefined, b: Browse | PlainMessage<Browse> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.Content
 */
export declare class Content extends Message<Content> {
  /**
   * @generated from field: youtube.response.browse.SingleColumnResultsRenderer singleColumnResultsRenderer = 58173949;
   */
  singleColumnResultsRenderer?: SingleColumnResultsRenderer;

  /**
   * @generated from field: youtube.response.browse.ElementRenderer elementRenderer = 153515154;
   */
  elementRenderer?: ElementRenderer;

  /**
   * @generated from field: youtube.response.browse.SectionListRenderer sectionListRenderer = 49399797;
   */
  sectionListRenderer?: SectionListRenderer;

  constructor(data?: PartialMessage<Content>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Content";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Content;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Content;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Content;

  static equals(a: Content | PlainMessage<Content> | undefined, b: Content | PlainMessage<Content> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.SingleColumnResultsRenderer
 */
export declare class SingleColumnResultsRenderer extends Message<SingleColumnResultsRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.BrowseTabSupportedRenderer tabs = 1;
   */
  tabs: BrowseTabSupportedRenderer[];

  constructor(data?: PartialMessage<SingleColumnResultsRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.SingleColumnResultsRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SingleColumnResultsRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SingleColumnResultsRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SingleColumnResultsRenderer;

  static equals(a: SingleColumnResultsRenderer | PlainMessage<SingleColumnResultsRenderer> | undefined, b: SingleColumnResultsRenderer | PlainMessage<SingleColumnResultsRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.BrowseTabSupportedRenderer
 */
export declare class BrowseTabSupportedRenderer extends Message<BrowseTabSupportedRenderer> {
  /**
   * @generated from field: youtube.response.browse.TabRenderer tabRenderer = 58174010;
   */
  tabRenderer?: TabRenderer;

  constructor(data?: PartialMessage<BrowseTabSupportedRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.BrowseTabSupportedRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BrowseTabSupportedRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BrowseTabSupportedRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BrowseTabSupportedRenderer;

  static equals(a: BrowseTabSupportedRenderer | PlainMessage<BrowseTabSupportedRenderer> | undefined, b: BrowseTabSupportedRenderer | PlainMessage<BrowseTabSupportedRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.TabRenderer
 */
export declare class TabRenderer extends Message<TabRenderer> {
  /**
   * @generated from field: youtube.response.browse.Content content = 4;
   */
  content?: Content;

  constructor(data?: PartialMessage<TabRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.TabRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TabRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TabRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TabRenderer;

  static equals(a: TabRenderer | PlainMessage<TabRenderer> | undefined, b: TabRenderer | PlainMessage<TabRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.SectionListRenderer
 */
export declare class SectionListRenderer extends Message<SectionListRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.SectionListSupportedRenderer sectionListSupportedRenderers = 1;
   */
  sectionListSupportedRenderers: SectionListSupportedRenderer[];

  constructor(data?: PartialMessage<SectionListRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.SectionListRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SectionListRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SectionListRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SectionListRenderer;

  static equals(a: SectionListRenderer | PlainMessage<SectionListRenderer> | undefined, b: SectionListRenderer | PlainMessage<SectionListRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.SectionListSupportedRenderer
 */
export declare class SectionListSupportedRenderer extends Message<SectionListSupportedRenderer> {
  /**
   * @generated from field: youtube.response.browse.ItemSectionRenderer itemSectionRenderer = 50195462;
   */
  itemSectionRenderer?: ItemSectionRenderer;

  /**
   * @generated from field: youtube.response.browse.ShelfRenderer shelfRenderer = 51845067;
   */
  shelfRenderer?: ShelfRenderer;

  /**
   * @generated from field: youtube.response.browse.MusicDescriptionShelfRenderer musicDescriptionShelfRenderer = 221496734;
   */
  musicDescriptionShelfRenderer?: MusicDescriptionShelfRenderer;

  constructor(data?: PartialMessage<SectionListSupportedRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.SectionListSupportedRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SectionListSupportedRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SectionListSupportedRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SectionListSupportedRenderer;

  static equals(a: SectionListSupportedRenderer | PlainMessage<SectionListSupportedRenderer> | undefined, b: SectionListSupportedRenderer | PlainMessage<SectionListSupportedRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.ItemSectionRenderer
 */
export declare class ItemSectionRenderer extends Message<ItemSectionRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.RichItemContent richItemContent = 1;
   */
  richItemContent: RichItemContent[];

  constructor(data?: PartialMessage<ItemSectionRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.ItemSectionRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ItemSectionRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ItemSectionRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ItemSectionRenderer;

  static equals(a: ItemSectionRenderer | PlainMessage<ItemSectionRenderer> | undefined, b: ItemSectionRenderer | PlainMessage<ItemSectionRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RichItemContent
 */
export declare class RichItemContent extends Message<RichItemContent> {
  /**
   * @generated from field: youtube.response.browse.ElementRenderer videoWithContextRenderer = 153515154;
   */
  videoWithContextRenderer?: ElementRenderer;

  constructor(data?: PartialMessage<RichItemContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RichItemContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RichItemContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RichItemContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RichItemContent;

  static equals(a: RichItemContent | PlainMessage<RichItemContent> | undefined, b: RichItemContent | PlainMessage<RichItemContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.ElementRenderer
 */
export declare class ElementRenderer extends Message<ElementRenderer> {
  /**
   * @generated from field: youtube.response.browse.VideoRendererContent videoRendererContent = 172660663;
   */
  videoRendererContent?: VideoRendererContent;

  constructor(data?: PartialMessage<ElementRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.ElementRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ElementRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ElementRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ElementRenderer;

  static equals(a: ElementRenderer | PlainMessage<ElementRenderer> | undefined, b: ElementRenderer | PlainMessage<ElementRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoRendererContent
 */
export declare class VideoRendererContent extends Message<VideoRendererContent> {
  /**
   * @generated from field: youtube.response.browse.VideoInfo videoInfo = 1;
   */
  videoInfo?: VideoInfo;

  /**
   * @generated from field: youtube.response.browse.RenderInfo renderInfo = 2;
   */
  renderInfo?: RenderInfo;

  constructor(data?: PartialMessage<VideoRendererContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoRendererContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoRendererContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoRendererContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoRendererContent;

  static equals(a: VideoRendererContent | PlainMessage<VideoRendererContent> | undefined, b: VideoRendererContent | PlainMessage<VideoRendererContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoInfo
 */
export declare class VideoInfo extends Message<VideoInfo> {
  /**
   * @generated from field: youtube.response.browse.VideoContext videoContext = 168777401;
   */
  videoContext?: VideoContext;

  constructor(data?: PartialMessage<VideoInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoInfo;

  static equals(a: VideoInfo | PlainMessage<VideoInfo> | undefined, b: VideoInfo | PlainMessage<VideoInfo> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoContext
 */
export declare class VideoContext extends Message<VideoContext> {
  /**
   * @generated from field: youtube.response.browse.VideoContent videoContent = 5;
   */
  videoContent?: VideoContent;

  constructor(data?: PartialMessage<VideoContext>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoContext";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoContext;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoContext;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoContext;

  static equals(a: VideoContext | PlainMessage<VideoContext> | undefined, b: VideoContext | PlainMessage<VideoContext> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.VideoContent
 */
export declare class VideoContent extends Message<VideoContent> {
  /**
   * @generated from field: youtube.response.browse.TimedLyricsRender timedLyricsRender = 465160965;
   */
  timedLyricsRender?: TimedLyricsRender;

  constructor(data?: PartialMessage<VideoContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.VideoContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VideoContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VideoContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VideoContent;

  static equals(a: VideoContent | PlainMessage<VideoContent> | undefined, b: VideoContent | PlainMessage<VideoContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.TimedLyricsRender
 */
export declare class TimedLyricsRender extends Message<TimedLyricsRender> {
  /**
   * @generated from field: youtube.response.browse.TimedLyricsContent timedLyricsContent = 4;
   */
  timedLyricsContent?: TimedLyricsContent;

  constructor(data?: PartialMessage<TimedLyricsRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.TimedLyricsRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimedLyricsRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimedLyricsRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimedLyricsRender;

  static equals(a: TimedLyricsRender | PlainMessage<TimedLyricsRender> | undefined, b: TimedLyricsRender | PlainMessage<TimedLyricsRender> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.TimedLyricsContent
 */
export declare class TimedLyricsContent extends Message<TimedLyricsContent> {
  /**
   * @generated from field: repeated youtube.component.Run runs = 1;
   */
  runs: Run[];

  /**
   * @generated from field: string footerLabel = 2;
   */
  footerLabel: string;

  constructor(data?: PartialMessage<TimedLyricsContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.TimedLyricsContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimedLyricsContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimedLyricsContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimedLyricsContent;

  static equals(a: TimedLyricsContent | PlainMessage<TimedLyricsContent> | undefined, b: TimedLyricsContent | PlainMessage<TimedLyricsContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RenderInfo
 */
export declare class RenderInfo extends Message<RenderInfo> {
  /**
   * @generated from field: youtube.response.browse.LayoutRender layoutRender = 183314536;
   */
  layoutRender?: LayoutRender;

  constructor(data?: PartialMessage<RenderInfo>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RenderInfo";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RenderInfo;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RenderInfo;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RenderInfo;

  static equals(a: RenderInfo | PlainMessage<RenderInfo> | undefined, b: RenderInfo | PlainMessage<RenderInfo> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.LayoutRender
 */
export declare class LayoutRender extends Message<LayoutRender> {
  /**
   * @generated from field: string eml = 1;
   */
  eml: string;

  constructor(data?: PartialMessage<LayoutRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.LayoutRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LayoutRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LayoutRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LayoutRender;

  static equals(a: LayoutRender | PlainMessage<LayoutRender> | undefined, b: LayoutRender | PlainMessage<LayoutRender> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.ShelfRenderer
 */
export declare class ShelfRenderer extends Message<ShelfRenderer> {
  /**
   * @generated from field: youtube.response.browse.RichSectionContent richSectionContent = 5;
   */
  richSectionContent?: RichSectionContent;

  constructor(data?: PartialMessage<ShelfRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.ShelfRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ShelfRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ShelfRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ShelfRenderer;

  static equals(a: ShelfRenderer | PlainMessage<ShelfRenderer> | undefined, b: ShelfRenderer | PlainMessage<ShelfRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RichSectionContent
 */
export declare class RichSectionContent extends Message<RichSectionContent> {
  /**
   * @generated from field: youtube.response.browse.ReelShelfRenderer reelShelfRenderer = 51431404;
   */
  reelShelfRenderer?: ReelShelfRenderer;

  constructor(data?: PartialMessage<RichSectionContent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RichSectionContent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RichSectionContent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RichSectionContent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RichSectionContent;

  static equals(a: RichSectionContent | PlainMessage<RichSectionContent> | undefined, b: RichSectionContent | PlainMessage<RichSectionContent> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.ReelShelfRenderer
 */
export declare class ReelShelfRenderer extends Message<ReelShelfRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.RichItemContent richItemContent = 1;
   */
  richItemContent: RichItemContent[];

  constructor(data?: PartialMessage<ReelShelfRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.ReelShelfRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReelShelfRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReelShelfRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReelShelfRenderer;

  static equals(a: ReelShelfRenderer | PlainMessage<ReelShelfRenderer> | undefined, b: ReelShelfRenderer | PlainMessage<ReelShelfRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.MusicDescriptionShelfRenderer
 */
export declare class MusicDescriptionShelfRenderer extends Message<MusicDescriptionShelfRenderer> {
  /**
   * @generated from field: youtube.component.Label description = 3;
   */
  description?: Label;

  /**
   * @generated from field: youtube.component.Label footer = 10;
   */
  footer?: Label;

  constructor(data?: PartialMessage<MusicDescriptionShelfRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.MusicDescriptionShelfRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MusicDescriptionShelfRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MusicDescriptionShelfRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MusicDescriptionShelfRenderer;

  static equals(a: MusicDescriptionShelfRenderer | PlainMessage<MusicDescriptionShelfRenderer> | undefined, b: MusicDescriptionShelfRenderer | PlainMessage<MusicDescriptionShelfRenderer> | undefined): boolean;
}

