// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/guide.proto (package youtube.response.browse, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.browse.Guide
 */
export declare class Guide extends Message<Guide> {
  /**
   * @generated from field: repeated youtube.response.browse.Item items4 = 4;
   */
  items4: Item[];

  /**
   * @generated from field: repeated youtube.response.browse.Item items6 = 6;
   */
  items6: Item[];

  constructor(data?: PartialMessage<Guide>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Guide";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Guide;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Guide;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Guide;

  static equals(a: Guide | PlainMessage<Guide> | undefined, b: Guide | PlainMessage<Guide> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.Item
 */
export declare class Item extends Message<Item> {
  /**
   * @generated from field: youtube.response.browse.GuideSectionRenderer guideSectionRenderer = 117866661;
   */
  guideSectionRenderer?: GuideSectionRenderer;

  constructor(data?: PartialMessage<Item>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.Item";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Item;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Item;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Item;

  static equals(a: Item | PlainMessage<Item> | undefined, b: Item | PlainMessage<Item> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.GuideSectionRenderer
 */
export declare class GuideSectionRenderer extends Message<GuideSectionRenderer> {
  /**
   * @generated from field: repeated youtube.response.browse.RendererItem rendererItems = 1;
   */
  rendererItems: RendererItem[];

  constructor(data?: PartialMessage<GuideSectionRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.GuideSectionRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GuideSectionRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GuideSectionRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GuideSectionRenderer;

  static equals(a: GuideSectionRenderer | PlainMessage<GuideSectionRenderer> | undefined, b: GuideSectionRenderer | PlainMessage<GuideSectionRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.RendererItem
 */
export declare class RendererItem extends Message<RendererItem> {
  /**
   * @generated from field: youtube.response.browse.guideEntryRenderer iconRender = 318370163;
   */
  iconRender?: guideEntryRenderer;

  /**
   * @generated from field: youtube.response.browse.guideEntryRenderer labelRender = 117501096;
   */
  labelRender?: guideEntryRenderer;

  constructor(data?: PartialMessage<RendererItem>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.RendererItem";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RendererItem;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RendererItem;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RendererItem;

  static equals(a: RendererItem | PlainMessage<RendererItem> | undefined, b: RendererItem | PlainMessage<RendererItem> | undefined): boolean;
}

/**
 * @generated from message youtube.response.browse.guideEntryRenderer
 */
export declare class guideEntryRenderer extends Message<guideEntryRenderer> {
  /**
   * @generated from field: string browseId = 1;
   */
  browseId: string;

  constructor(data?: PartialMessage<guideEntryRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.browse.guideEntryRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): guideEntryRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): guideEntryRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): guideEntryRenderer;

  static equals(a: guideEntryRenderer | PlainMessage<guideEntryRenderer> | undefined, b: guideEntryRenderer | PlainMessage<guideEntryRenderer> | undefined): boolean;
}

