// @generated by protoc-gen-es v1.7.2
// @generated from file response/next.proto (package youtube.response.next, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Contents as Contents$1 } from "./browse_pb.js";

/**
 * @generated from message youtube.response.next.Next
 */
export const Next = proto3.makeMessageType(
  "youtube.response.next.Next",
  () => [
    { no: 7, name: "Contents", kind: "message", T: Contents },
    { no: 8, name: "onResponseReceivedActions", kind: "message", T: Contents$1 },
  ],
);

/**
 * @generated from message youtube.response.next.Contents
 */
export const Contents = proto3.makeMessageType(
  "youtube.response.next.Contents",
  () => [
    { no: 51779735, name: "NextResults", kind: "message", T: NextResults },
  ],
);

/**
 * @generated from message youtube.response.next.NextResults
 */
export const NextResults = proto3.makeMessageType(
  "youtube.response.next.NextResults",
  () => [
    { no: 1, name: "Contents", kind: "message", T: Contents$1 },
  ],
);

