// @generated by protoc-gen-es v1.7.2
// @generated from file response/next.proto (package youtube.response.next, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Contents as Contents$1 } from "./browse_pb.js";
import type { FrameworkUpdateTransport } from "./frameworkUpdate_pb.js";

/**
 * @generated from message youtube.response.next.Next
 */
export declare class Next extends Message<Next> {
  /**
   * @generated from field: youtube.response.next.Contents Contents = 7;
   */
  Contents?: Contents;

  /**
   * @generated from field: youtube.response.browse.Contents onResponseReceivedActions = 8;
   */
  onResponseReceivedActions?: Contents$1;

  /**
   * @generated from field: youtube.response.frameworkUpdate.FrameworkUpdateTransport frameworkUpdateTransport = 777;
   */
  frameworkUpdateTransport?: FrameworkUpdateTransport;

  constructor(data?: PartialMessage<Next>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.Next";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Next;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Next;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Next;

  static equals(a: Next | PlainMessage<Next> | undefined, b: Next | PlainMessage<Next> | undefined): boolean;
}

/**
 * @generated from message youtube.response.next.Contents
 */
export declare class Contents extends Message<Contents> {
  /**
   * @generated from field: youtube.response.next.NextResults NextResults = 51779735;
   */
  NextResults?: NextResults;

  constructor(data?: PartialMessage<Contents>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.Contents";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Contents;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Contents;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Contents;

  static equals(a: Contents | PlainMessage<Contents> | undefined, b: Contents | PlainMessage<Contents> | undefined): boolean;
}

/**
 * @generated from message youtube.response.next.NextResults
 */
export declare class NextResults extends Message<NextResults> {
  /**
   * @generated from field: youtube.response.browse.Contents Contents = 1;
   */
  Contents?: Contents$1;

  constructor(data?: PartialMessage<NextResults>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.NextResults";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NextResults;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NextResults;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NextResults;

  static equals(a: NextResults | PlainMessage<NextResults> | undefined, b: NextResults | PlainMessage<NextResults> | undefined): boolean;
}

