// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/next.proto (package youtube.response.next, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Content as Content$1 } from "./browse_pb.js";
import type { FrameworkUpdateTransport } from "../component/framework_pb.js";

/**
 * @generated from message youtube.response.next.Next
 */
export declare class Next extends Message<Next> {
  /**
   * @generated from field: youtube.response.next.Content content = 7;
   */
  content?: Content;

  /**
   * @generated from field: youtube.response.browse.Content onResponseReceivedAction = 8;
   */
  onResponseReceivedAction?: Content$1;

  /**
   * @generated from field: youtube.component.FrameworkUpdateTransport frameworkUpdateTransport = 777;
   */
  frameworkUpdateTransport?: FrameworkUpdateTransport;

  constructor(data?: PartialMessage<Next>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.Next";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Next;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Next;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Next;

  static equals(a: Next | PlainMessage<Next> | undefined, b: Next | PlainMessage<Next> | undefined): boolean;
}

/**
 * @generated from message youtube.response.next.Content
 */
export declare class Content extends Message<Content> {
  /**
   * @generated from field: youtube.response.next.NextResult nextResult = 51779735;
   */
  nextResult?: NextResult;

  constructor(data?: PartialMessage<Content>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.Content";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Content;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Content;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Content;

  static equals(a: Content | PlainMessage<Content> | undefined, b: Content | PlainMessage<Content> | undefined): boolean;
}

/**
 * @generated from message youtube.response.next.NextResult
 */
export declare class NextResult extends Message<NextResult> {
  /**
   * @generated from field: youtube.response.browse.Content content = 1;
   */
  content?: Content$1;

  constructor(data?: PartialMessage<NextResult>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.next.NextResult";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NextResult;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NextResult;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NextResult;

  static equals(a: NextResult | PlainMessage<NextResult> | undefined, b: NextResult | PlainMessage<NextResult> | undefined): boolean;
}

