// @generated by protoc-gen-es v1.7.2
// @generated from file response/player.proto (package youtube.response.player, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.player.Player
 */
export declare class Player extends Message<Player> {
  /**
   * @generated from field: repeated youtube.response.player.AdPlacement adPlacements = 7;
   */
  adPlacements: AdPlacement[];

  /**
   * @generated from field: youtube.response.player.PlayabilityStatus playabilityStatus = 2;
   */
  playabilityStatus?: PlayabilityStatus;

  /**
   * @generated from field: youtube.response.player.Captions captions = 10;
   */
  captions?: Captions;

  constructor(data?: PartialMessage<Player>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Player";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player;

  static equals(a: Player | PlainMessage<Player> | undefined, b: Player | PlainMessage<Player> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdPlacement
 */
export declare class AdPlacement extends Message<AdPlacement> {
  /**
   * @generated from field: youtube.response.player.AdPlacementRenderer adPlacementRenderer = 84813246;
   */
  adPlacementRenderer?: AdPlacementRenderer;

  constructor(data?: PartialMessage<AdPlacement>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdPlacement";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdPlacement;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdPlacement;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdPlacement;

  static equals(a: AdPlacement | PlainMessage<AdPlacement> | undefined, b: AdPlacement | PlainMessage<AdPlacement> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdPlacementRenderer
 */
export declare class AdPlacementRenderer extends Message<AdPlacementRenderer> {
  /**
   * @generated from field: string params = 4;
   */
  params: string;

  constructor(data?: PartialMessage<AdPlacementRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdPlacementRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdPlacementRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdPlacementRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdPlacementRenderer;

  static equals(a: AdPlacementRenderer | PlainMessage<AdPlacementRenderer> | undefined, b: AdPlacementRenderer | PlainMessage<AdPlacementRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PlayabilityStatus
 */
export declare class PlayabilityStatus extends Message<PlayabilityStatus> {
  /**
   * @generated from field: youtube.response.player.PIPAbility pipAbility = 21;
   */
  pipAbility?: PIPAbility;

  /**
   * @generated from field: youtube.response.player.BackgroundAbility backgroundAbility = 11;
   */
  backgroundAbility?: BackgroundAbility;

  constructor(data?: PartialMessage<PlayabilityStatus>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PlayabilityStatus";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayabilityStatus;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayabilityStatus;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayabilityStatus;

  static equals(a: PlayabilityStatus | PlainMessage<PlayabilityStatus> | undefined, b: PlayabilityStatus | PlainMessage<PlayabilityStatus> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PIPAbility
 */
export declare class PIPAbility extends Message<PIPAbility> {
  /**
   * @generated from field: youtube.response.player.PIPlayer piplayer = 151635310;
   */
  piplayer?: PIPlayer;

  constructor(data?: PartialMessage<PIPAbility>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PIPAbility";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PIPAbility;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PIPAbility;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PIPAbility;

  static equals(a: PIPAbility | PlainMessage<PIPAbility> | undefined, b: PIPAbility | PlainMessage<PIPAbility> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.BackgroundAbility
 */
export declare class BackgroundAbility extends Message<BackgroundAbility> {
  /**
   * @generated from field: youtube.response.player.BackgroundPlayer backgroundPlayer = 64657230;
   */
  backgroundPlayer?: BackgroundPlayer;

  constructor(data?: PartialMessage<BackgroundAbility>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.BackgroundAbility";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundAbility;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundAbility;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundAbility;

  static equals(a: BackgroundAbility | PlainMessage<BackgroundAbility> | undefined, b: BackgroundAbility | PlainMessage<BackgroundAbility> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PIPlayer
 */
export declare class PIPlayer extends Message<PIPlayer> {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;

  constructor(data?: PartialMessage<PIPlayer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PIPlayer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PIPlayer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PIPlayer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PIPlayer;

  static equals(a: PIPlayer | PlainMessage<PIPlayer> | undefined, b: PIPlayer | PlainMessage<PIPlayer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.BackgroundPlayer
 */
export declare class BackgroundPlayer extends Message<BackgroundPlayer> {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;

  constructor(data?: PartialMessage<BackgroundPlayer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.BackgroundPlayer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundPlayer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundPlayer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundPlayer;

  static equals(a: BackgroundPlayer | PlainMessage<BackgroundPlayer> | undefined, b: BackgroundPlayer | PlainMessage<BackgroundPlayer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Captions
 */
export declare class Captions extends Message<Captions> {
  /**
   * @generated from field: youtube.response.player.PlayerCaptionsTracklistRenderer playerCaptionsTracklistRenderer = 51621377;
   */
  playerCaptionsTracklistRenderer?: PlayerCaptionsTracklistRenderer;

  constructor(data?: PartialMessage<Captions>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Captions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Captions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Captions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Captions;

  static equals(a: Captions | PlainMessage<Captions> | undefined, b: Captions | PlainMessage<Captions> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PlayerCaptionsTracklistRenderer
 */
export declare class PlayerCaptionsTracklistRenderer extends Message<PlayerCaptionsTracklistRenderer> {
  /**
   * @generated from field: repeated youtube.response.player.CaptionTracks captionTracks = 1;
   */
  captionTracks: CaptionTracks[];

  /**
   * @generated from field: repeated youtube.response.player.AudioTracks audioTracks = 2;
   */
  audioTracks: AudioTracks[];

  /**
   * @generated from field: repeated youtube.response.player.TranslationLanguage translationLanguages = 3;
   */
  translationLanguages: TranslationLanguage[];

  /**
   * @generated from field: optional int32 defaultAudioTrackIndex = 4;
   */
  defaultAudioTrackIndex?: number;

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 6;
   */
  defaultCaptionTrackIndex?: number;

  constructor(data?: PartialMessage<PlayerCaptionsTracklistRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PlayerCaptionsTracklistRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayerCaptionsTracklistRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayerCaptionsTracklistRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayerCaptionsTracklistRenderer;

  static equals(a: PlayerCaptionsTracklistRenderer | PlainMessage<PlayerCaptionsTracklistRenderer> | undefined, b: PlayerCaptionsTracklistRenderer | PlainMessage<PlayerCaptionsTracklistRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.CaptionTracks
 */
export declare class CaptionTracks extends Message<CaptionTracks> {
  /**
   * @generated from field: string baseUrl = 1;
   */
  baseUrl: string;

  /**
   * @generated from field: youtube.response.player.Name name = 2;
   */
  name?: Name;

  /**
   * @generated from field: string vssId = 3;
   */
  vssId: string;

  /**
   * @generated from field: string languageCode = 4;
   */
  languageCode: string;

  /**
   * @generated from field: optional string kind = 5;
   */
  kind?: string;

  /**
   * @generated from field: optional bool rtl = 6;
   */
  rtl?: boolean;

  /**
   * @generated from field: bool isTranslatable = 7;
   */
  isTranslatable: boolean;

  constructor(data?: PartialMessage<CaptionTracks>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.CaptionTracks";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptionTracks;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptionTracks;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptionTracks;

  static equals(a: CaptionTracks | PlainMessage<CaptionTracks> | undefined, b: CaptionTracks | PlainMessage<CaptionTracks> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AudioTracks
 */
export declare class AudioTracks extends Message<AudioTracks> {
  /**
   * @generated from field: repeated int32 captionTrackIndices = 2 [packed = false];
   */
  captionTrackIndices: number[];

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 3;
   */
  defaultCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 forcedCaptionTrackIndex = 4;
   */
  forcedCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 visibility = 5;
   */
  visibility?: number;

  /**
   * @generated from field: optional bool hasDefaultTrack = 6;
   */
  hasDefaultTrack?: boolean;

  /**
   * @generated from field: optional bool hasForcedTrack = 7;
   */
  hasForcedTrack?: boolean;

  /**
   * @generated from field: optional string audioTrackId = 8;
   */
  audioTrackId?: string;

  /**
   * @generated from field: optional int32 captionsInitialState = 11;
   */
  captionsInitialState?: number;

  constructor(data?: PartialMessage<AudioTracks>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AudioTracks";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AudioTracks;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AudioTracks;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AudioTracks;

  static equals(a: AudioTracks | PlainMessage<AudioTracks> | undefined, b: AudioTracks | PlainMessage<AudioTracks> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.TranslationLanguage
 */
export declare class TranslationLanguage extends Message<TranslationLanguage> {
  /**
   * @generated from field: string languageCode = 1;
   */
  languageCode: string;

  /**
   * @generated from field: youtube.response.player.Name languageName = 2;
   */
  languageName?: Name;

  constructor(data?: PartialMessage<TranslationLanguage>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.TranslationLanguage";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TranslationLanguage;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TranslationLanguage;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TranslationLanguage;

  static equals(a: TranslationLanguage | PlainMessage<TranslationLanguage> | undefined, b: TranslationLanguage | PlainMessage<TranslationLanguage> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Name
 */
export declare class Name extends Message<Name> {
  /**
   * @generated from field: repeated youtube.response.player.Name.Runs runs = 1;
   */
  runs: Name_Runs[];

  constructor(data?: PartialMessage<Name>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Name";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Name;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Name;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Name;

  static equals(a: Name | PlainMessage<Name> | undefined, b: Name | PlainMessage<Name> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Name.Runs
 */
export declare class Name_Runs extends Message<Name_Runs> {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  constructor(data?: PartialMessage<Name_Runs>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Name.Runs";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Name_Runs;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Name_Runs;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Name_Runs;

  static equals(a: Name_Runs | PlainMessage<Name_Runs> | undefined, b: Name_Runs | PlainMessage<Name_Runs> | undefined): boolean;
}

