// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/player.proto (package youtube.response.player, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Label } from "../component/label_pb.js";

/**
 * @generated from message youtube.response.player.Player
 */
export declare class Player extends Message<Player> {
  /**
   * @generated from field: repeated youtube.response.player.AdPlacement adPlacements = 7;
   */
  adPlacements: AdPlacement[];

  /**
   * @generated from field: youtube.response.player.PlayabilityStatus playabilityStatus = 2;
   */
  playabilityStatus?: PlayabilityStatus;

  /**
   * @generated from field: youtube.response.player.PlaybackTracking playbackTracking = 9;
   */
  playbackTracking?: PlaybackTracking;

  /**
   * @generated from field: youtube.response.player.Captions captions = 10;
   */
  captions?: Captions;

  /**
   * @generated from field: repeated youtube.response.player.AdSlot adSlots = 68;
   */
  adSlots: AdSlot[];

  constructor(data?: PartialMessage<Player>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Player";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Player;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Player;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Player;

  static equals(a: Player | PlainMessage<Player> | undefined, b: Player | PlainMessage<Player> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdPlacement
 */
export declare class AdPlacement extends Message<AdPlacement> {
  /**
   * @generated from field: youtube.response.player.AdPlacementRenderer adPlacementRenderer = 84813246;
   */
  adPlacementRenderer?: AdPlacementRenderer;

  constructor(data?: PartialMessage<AdPlacement>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdPlacement";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdPlacement;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdPlacement;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdPlacement;

  static equals(a: AdPlacement | PlainMessage<AdPlacement> | undefined, b: AdPlacement | PlainMessage<AdPlacement> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdPlacementRenderer
 */
export declare class AdPlacementRenderer extends Message<AdPlacementRenderer> {
  /**
   * @generated from field: string params = 4;
   */
  params: string;

  constructor(data?: PartialMessage<AdPlacementRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdPlacementRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdPlacementRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdPlacementRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdPlacementRenderer;

  static equals(a: AdPlacementRenderer | PlainMessage<AdPlacementRenderer> | undefined, b: AdPlacementRenderer | PlainMessage<AdPlacementRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PlayabilityStatus
 */
export declare class PlayabilityStatus extends Message<PlayabilityStatus> {
  /**
   * @generated from field: youtube.response.player.MiniPlayer miniPlayer = 21;
   */
  miniPlayer?: MiniPlayer;

  /**
   * @generated from field: youtube.response.player.BackgroundPlayer backgroundPlayer = 11;
   */
  backgroundPlayer?: BackgroundPlayer;

  constructor(data?: PartialMessage<PlayabilityStatus>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PlayabilityStatus";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayabilityStatus;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayabilityStatus;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayabilityStatus;

  static equals(a: PlayabilityStatus | PlainMessage<PlayabilityStatus> | undefined, b: PlayabilityStatus | PlainMessage<PlayabilityStatus> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.MiniPlayer
 */
export declare class MiniPlayer extends Message<MiniPlayer> {
  /**
   * @generated from field: youtube.response.player.MiniPlayerRender miniPlayerRender = 151635310;
   */
  miniPlayerRender?: MiniPlayerRender;

  constructor(data?: PartialMessage<MiniPlayer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.MiniPlayer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MiniPlayer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MiniPlayer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MiniPlayer;

  static equals(a: MiniPlayer | PlainMessage<MiniPlayer> | undefined, b: MiniPlayer | PlainMessage<MiniPlayer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.BackgroundPlayer
 */
export declare class BackgroundPlayer extends Message<BackgroundPlayer> {
  /**
   * @generated from field: youtube.response.player.BackgroundPlayerRender backgroundPlayerRender = 64657230;
   */
  backgroundPlayerRender?: BackgroundPlayerRender;

  constructor(data?: PartialMessage<BackgroundPlayer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.BackgroundPlayer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundPlayer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundPlayer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundPlayer;

  static equals(a: BackgroundPlayer | PlainMessage<BackgroundPlayer> | undefined, b: BackgroundPlayer | PlainMessage<BackgroundPlayer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.MiniPlayerRender
 */
export declare class MiniPlayerRender extends Message<MiniPlayerRender> {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;

  constructor(data?: PartialMessage<MiniPlayerRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.MiniPlayerRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MiniPlayerRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MiniPlayerRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MiniPlayerRender;

  static equals(a: MiniPlayerRender | PlainMessage<MiniPlayerRender> | undefined, b: MiniPlayerRender | PlainMessage<MiniPlayerRender> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.BackgroundPlayerRender
 */
export declare class BackgroundPlayerRender extends Message<BackgroundPlayerRender> {
  /**
   * @generated from field: bool active = 1;
   */
  active: boolean;

  constructor(data?: PartialMessage<BackgroundPlayerRender>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.BackgroundPlayerRender";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundPlayerRender;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundPlayerRender;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundPlayerRender;

  static equals(a: BackgroundPlayerRender | PlainMessage<BackgroundPlayerRender> | undefined, b: BackgroundPlayerRender | PlainMessage<BackgroundPlayerRender> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PlaybackTracking
 */
export declare class PlaybackTracking extends Message<PlaybackTracking> {
  /**
   * @generated from field: youtube.response.player.Tracking videostatsPlaybackUrl = 1;
   */
  videostatsPlaybackUrl?: Tracking;

  /**
   * @generated from field: youtube.response.player.Tracking videostatsDelayplayUrl = 2;
   */
  videostatsDelayplayUrl?: Tracking;

  /**
   * @generated from field: youtube.response.player.Tracking videostatsWatchtimeUrl = 3;
   */
  videostatsWatchtimeUrl?: Tracking;

  /**
   * @generated from field: youtube.response.player.Tracking ptrackingUrl = 4;
   */
  ptrackingUrl?: Tracking;

  /**
   * @generated from field: youtube.response.player.Tracking qoeUrl = 5;
   */
  qoeUrl?: Tracking;

  /**
   * @generated from field: youtube.response.player.Tracking atrUrl = 13;
   */
  atrUrl?: Tracking;

  /**
   * @generated from field: youtube.response.player.Tracking videostatsEngageUrl = 15;
   */
  videostatsEngageUrl?: Tracking;

  /**
   * @generated from field: youtube.response.player.Tracking pageadViewthroughconversion = 18;
   */
  pageadViewthroughconversion?: Tracking;

  constructor(data?: PartialMessage<PlaybackTracking>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PlaybackTracking";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlaybackTracking;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlaybackTracking;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlaybackTracking;

  static equals(a: PlaybackTracking | PlainMessage<PlaybackTracking> | undefined, b: PlaybackTracking | PlainMessage<PlaybackTracking> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Tracking
 */
export declare class Tracking extends Message<Tracking> {
  /**
   * @generated from field: string baseUrl = 1;
   */
  baseUrl: string;

  constructor(data?: PartialMessage<Tracking>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Tracking";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Tracking;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Tracking;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Tracking;

  static equals(a: Tracking | PlainMessage<Tracking> | undefined, b: Tracking | PlainMessage<Tracking> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.Captions
 */
export declare class Captions extends Message<Captions> {
  /**
   * @generated from field: youtube.response.player.PlayerCaptionsTrackListRenderer playerCaptionsTrackListRenderer = 51621377 [json_name = "playerCaptionsTracklistRenderer"];
   */
  playerCaptionsTrackListRenderer?: PlayerCaptionsTrackListRenderer;

  constructor(data?: PartialMessage<Captions>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.Captions";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Captions;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Captions;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Captions;

  static equals(a: Captions | PlainMessage<Captions> | undefined, b: Captions | PlainMessage<Captions> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.PlayerCaptionsTrackListRenderer
 */
export declare class PlayerCaptionsTrackListRenderer extends Message<PlayerCaptionsTrackListRenderer> {
  /**
   * @generated from field: repeated youtube.response.player.CaptionTrack captionTracks = 1;
   */
  captionTracks: CaptionTrack[];

  /**
   * @generated from field: repeated youtube.response.player.AudioTrack audioTracks = 2;
   */
  audioTracks: AudioTrack[];

  /**
   * @generated from field: repeated youtube.response.player.TranslationLanguage translationLanguages = 3;
   */
  translationLanguages: TranslationLanguage[];

  /**
   * @generated from field: optional int32 defaultAudioTrackIndex = 4;
   */
  defaultAudioTrackIndex?: number;

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 6;
   */
  defaultCaptionTrackIndex?: number;

  constructor(data?: PartialMessage<PlayerCaptionsTrackListRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.PlayerCaptionsTrackListRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayerCaptionsTrackListRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayerCaptionsTrackListRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayerCaptionsTrackListRenderer;

  static equals(a: PlayerCaptionsTrackListRenderer | PlainMessage<PlayerCaptionsTrackListRenderer> | undefined, b: PlayerCaptionsTrackListRenderer | PlainMessage<PlayerCaptionsTrackListRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.CaptionTrack
 */
export declare class CaptionTrack extends Message<CaptionTrack> {
  /**
   * @generated from field: string baseUrl = 1;
   */
  baseUrl: string;

  /**
   * @generated from field: youtube.component.Label name = 2;
   */
  name?: Label;

  /**
   * @generated from field: string vssId = 3;
   */
  vssId: string;

  /**
   * @generated from field: string languageCode = 4;
   */
  languageCode: string;

  /**
   * @generated from field: optional string kind = 5;
   */
  kind?: string;

  /**
   * @generated from field: optional bool rtl = 6;
   */
  rtl?: boolean;

  /**
   * @generated from field: bool isTranslatable = 7;
   */
  isTranslatable: boolean;

  constructor(data?: PartialMessage<CaptionTrack>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.CaptionTrack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CaptionTrack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CaptionTrack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CaptionTrack;

  static equals(a: CaptionTrack | PlainMessage<CaptionTrack> | undefined, b: CaptionTrack | PlainMessage<CaptionTrack> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AudioTrack
 */
export declare class AudioTrack extends Message<AudioTrack> {
  /**
   * @generated from field: repeated int32 captionTrackIndices = 2 [packed = false];
   */
  captionTrackIndices: number[];

  /**
   * @generated from field: optional int32 defaultCaptionTrackIndex = 3;
   */
  defaultCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 forcedCaptionTrackIndex = 4;
   */
  forcedCaptionTrackIndex?: number;

  /**
   * @generated from field: optional int32 visibility = 5;
   */
  visibility?: number;

  /**
   * @generated from field: optional bool hasDefaultTrack = 6;
   */
  hasDefaultTrack?: boolean;

  /**
   * @generated from field: optional bool hasForcedTrack = 7;
   */
  hasForcedTrack?: boolean;

  /**
   * @generated from field: optional string audioTrackId = 8;
   */
  audioTrackId?: string;

  /**
   * @generated from field: optional int32 captionsInitialState = 11;
   */
  captionsInitialState?: number;

  constructor(data?: PartialMessage<AudioTrack>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AudioTrack";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AudioTrack;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AudioTrack;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AudioTrack;

  static equals(a: AudioTrack | PlainMessage<AudioTrack> | undefined, b: AudioTrack | PlainMessage<AudioTrack> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.TranslationLanguage
 */
export declare class TranslationLanguage extends Message<TranslationLanguage> {
  /**
   * @generated from field: string languageCode = 1;
   */
  languageCode: string;

  /**
   * @generated from field: youtube.component.Label languageName = 2;
   */
  languageName?: Label;

  constructor(data?: PartialMessage<TranslationLanguage>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.TranslationLanguage";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TranslationLanguage;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TranslationLanguage;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TranslationLanguage;

  static equals(a: TranslationLanguage | PlainMessage<TranslationLanguage> | undefined, b: TranslationLanguage | PlainMessage<TranslationLanguage> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdSlot
 */
export declare class AdSlot extends Message<AdSlot> {
  /**
   * @generated from field: youtube.response.player.AdSlot.Render render = 424701016;
   */
  render?: AdSlot_Render;

  constructor(data?: PartialMessage<AdSlot>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdSlot";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdSlot;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdSlot;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdSlot;

  static equals(a: AdSlot | PlainMessage<AdSlot> | undefined, b: AdSlot | PlainMessage<AdSlot> | undefined): boolean;
}

/**
 * @generated from message youtube.response.player.AdSlot.Render
 */
export declare class AdSlot_Render extends Message<AdSlot_Render> {
  constructor(data?: PartialMessage<AdSlot_Render>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.player.AdSlot.Render";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AdSlot_Render;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AdSlot_Render;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AdSlot_Render;

  static equals(a: AdSlot_Render | PlainMessage<AdSlot_Render> | undefined, b: AdSlot_Render | PlainMessage<AdSlot_Render> | undefined): boolean;
}

