// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/search.proto (package youtube.response.search, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Content, ItemSectionRenderer, SectionListRenderer } from "./browse_pb.js";

/**
 * @generated from message youtube.response.search.Search
 */
export declare class Search extends Message<Search> {
  /**
   * @generated from field: youtube.response.browse.Content content = 4;
   */
  content?: Content;

  /**
   * @generated from field: youtube.response.search.OnResponseReceivedCommand onResponseReceivedCommand = 7;
   */
  onResponseReceivedCommand?: OnResponseReceivedCommand;

  constructor(data?: PartialMessage<Search>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.search.Search";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Search;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Search;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Search;

  static equals(a: Search | PlainMessage<Search> | undefined, b: Search | PlainMessage<Search> | undefined): boolean;
}

/**
 * @generated from message youtube.response.search.OnResponseReceivedCommand
 */
export declare class OnResponseReceivedCommand extends Message<OnResponseReceivedCommand> {
  /**
   * @generated from field: youtube.response.browse.ItemSectionRenderer itemSectionRenderer = 50195462;
   */
  itemSectionRenderer?: ItemSectionRenderer;

  /**
   * @generated from field: youtube.response.browse.SectionListRenderer appendContinuationItemsAction = 49399797;
   */
  appendContinuationItemsAction?: SectionListRenderer;

  constructor(data?: PartialMessage<OnResponseReceivedCommand>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.search.OnResponseReceivedCommand";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OnResponseReceivedCommand;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OnResponseReceivedCommand;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OnResponseReceivedCommand;

  static equals(a: OnResponseReceivedCommand | PlainMessage<OnResponseReceivedCommand> | undefined, b: OnResponseReceivedCommand | PlainMessage<OnResponseReceivedCommand> | undefined): boolean;
}

