// @generated by protoc-gen-es v1.7.2
// @generated from file response/search.proto (package youtube.response.search, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Contents, RichGridRenderer, RichItemRenderer } from "./browse_pb.js";

/**
 * @generated from message youtube.response.search.Search
 */
export const Search = proto3.makeMessageType(
  "youtube.response.search.Search",
  () => [
    { no: 4, name: "contents", kind: "message", T: Contents },
    { no: 7, name: "onResponseReceivedCommands", kind: "message", T: OnResponseReceivedCommands },
  ],
);

/**
 * @generated from message youtube.response.search.OnResponseReceivedCommands
 */
export const OnResponseReceivedCommands = proto3.makeMessageType(
  "youtube.response.search.OnResponseReceivedCommands",
  () => [
    { no: 50195462, name: "richItemRenderer", kind: "message", T: RichItemRenderer },
    { no: 49399797, name: "appendContinuationItemsAction", kind: "message", T: RichGridRenderer },
  ],
);

