// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/search.proto (package youtube.response.search, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Content, ItemSectionRenderer, SectionListRenderer } from "./browse_pb.js";

/**
 * @generated from message youtube.response.search.Search
 */
export const Search = proto3.makeMessageType(
  "youtube.response.search.Search",
  () => [
    { no: 4, name: "content", kind: "message", T: Content },
    { no: 7, name: "onResponseReceivedCommand", kind: "message", T: OnResponseReceivedCommand },
  ],
);

/**
 * @generated from message youtube.response.search.OnResponseReceivedCommand
 */
export const OnResponseReceivedCommand = proto3.makeMessageType(
  "youtube.response.search.OnResponseReceivedCommand",
  () => [
    { no: 50195462, name: "itemSectionRenderer", kind: "message", T: ItemSectionRenderer },
    { no: 49399797, name: "appendContinuationItemsAction", kind: "message", T: SectionListRenderer },
  ],
);

