// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/setting.proto (package youtube.response.setting, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Label } from "../component/label_pb.js";

/**
 * @generated from message youtube.response.setting.Setting
 */
export declare class Setting extends Message<Setting> {
  /**
   * @generated from field: repeated youtube.response.setting.SettingItem settingItems = 6;
   */
  settingItems: SettingItem[];

  /**
   * @generated from field: repeated youtube.response.setting.SettingItem CollectionItems = 7;
   */
  CollectionItems: SettingItem[];

  constructor(data?: PartialMessage<Setting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.Setting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Setting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Setting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Setting;

  static equals(a: Setting | PlainMessage<Setting> | undefined, b: Setting | PlainMessage<Setting> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingItem
 */
export declare class SettingItem extends Message<SettingItem> {
  /**
   * @generated from field: youtube.response.setting.BackgroundPlayBackSettingRenderer backgroundPlayBackSettingRenderer = 88478200;
   */
  backgroundPlayBackSettingRenderer?: BackgroundPlayBackSettingRenderer;

  /**
   * @generated from field: youtube.response.setting.SettingCategoryCollectionRenderer settingCategoryCollectionRenderer = 66930374;
   */
  settingCategoryCollectionRenderer?: SettingCategoryCollectionRenderer;

  constructor(data?: PartialMessage<SettingItem>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingItem";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingItem;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingItem;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingItem;

  static equals(a: SettingItem | PlainMessage<SettingItem> | undefined, b: SettingItem | PlainMessage<SettingItem> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.BackgroundPlayBackSettingRenderer
 */
export declare class BackgroundPlayBackSettingRenderer extends Message<BackgroundPlayBackSettingRenderer> {
  /**
   * @generated from field: youtube.component.Label name = 1;
   */
  name?: Label;

  /**
   * @generated from field: bool backgroundPlayback = 2;
   */
  backgroundPlayback: boolean;

  /**
   * @generated from field: bool download = 3;
   */
  download: boolean;

  /**
   * @generated from field: bytes trackingParams = 5;
   */
  trackingParams: Uint8Array;

  /**
   * @generated from field: bool downloadQualitySelection = 9;
   */
  downloadQualitySelection: boolean;

  /**
   * @generated from field: bool smartDownload = 10;
   */
  smartDownload: boolean;

  /**
   * @generated from field: youtube.response.setting.Icon icon = 14;
   */
  icon?: Icon;

  constructor(data?: PartialMessage<BackgroundPlayBackSettingRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.BackgroundPlayBackSettingRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BackgroundPlayBackSettingRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BackgroundPlayBackSettingRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BackgroundPlayBackSettingRenderer;

  static equals(a: BackgroundPlayBackSettingRenderer | PlainMessage<BackgroundPlayBackSettingRenderer> | undefined, b: BackgroundPlayBackSettingRenderer | PlainMessage<BackgroundPlayBackSettingRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingCategoryCollectionRenderer
 */
export declare class SettingCategoryCollectionRenderer extends Message<SettingCategoryCollectionRenderer> {
  /**
   * @generated from field: youtube.component.Label name = 2;
   */
  name?: Label;

  /**
   * @generated from field: repeated youtube.response.setting.SubSetting subSettings = 3;
   */
  subSettings: SubSetting[];

  /**
   * @generated from field: int32 categoryId = 4;
   */
  categoryId: number;

  /**
   * @generated from field: youtube.response.setting.Icon icon = 5;
   */
  icon?: Icon;

  constructor(data?: PartialMessage<SettingCategoryCollectionRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingCategoryCollectionRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingCategoryCollectionRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingCategoryCollectionRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingCategoryCollectionRenderer;

  static equals(a: SettingCategoryCollectionRenderer | PlainMessage<SettingCategoryCollectionRenderer> | undefined, b: SettingCategoryCollectionRenderer | PlainMessage<SettingCategoryCollectionRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.Icon
 */
export declare class Icon extends Message<Icon> {
  /**
   * @generated from field: int32 iconType = 1;
   */
  iconType: number;

  constructor(data?: PartialMessage<Icon>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.Icon";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Icon;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Icon;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Icon;

  static equals(a: Icon | PlainMessage<Icon> | undefined, b: Icon | PlainMessage<Icon> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SubSetting
 */
export declare class SubSetting extends Message<SubSetting> {
  /**
   * @generated from field: youtube.response.setting.SettingBooleanRenderer settingBooleanRenderer = 61331416;
   */
  settingBooleanRenderer?: SettingBooleanRenderer;

  constructor(data?: PartialMessage<SubSetting>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SubSetting";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SubSetting;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SubSetting;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SubSetting;

  static equals(a: SubSetting | PlainMessage<SubSetting> | undefined, b: SubSetting | PlainMessage<SubSetting> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingBooleanRenderer
 */
export declare class SettingBooleanRenderer extends Message<SettingBooleanRenderer> {
  /**
   * @generated from field: youtube.component.Label title = 2;
   */
  title?: Label;

  /**
   * @generated from field: youtube.component.Label description = 3;
   */
  description?: Label;

  /**
   * @generated from field: youtube.response.setting.ServiceEndpoint enableServiceEndpoint = 5;
   */
  enableServiceEndpoint?: ServiceEndpoint;

  /**
   * @generated from field: youtube.response.setting.ServiceEndpoint disableServiceEndpoint = 6;
   */
  disableServiceEndpoint?: ServiceEndpoint;

  /**
   * @generated from field: int32 itemId = 15;
   */
  itemId: number;

  constructor(data?: PartialMessage<SettingBooleanRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingBooleanRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingBooleanRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingBooleanRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingBooleanRenderer;

  static equals(a: SettingBooleanRenderer | PlainMessage<SettingBooleanRenderer> | undefined, b: SettingBooleanRenderer | PlainMessage<SettingBooleanRenderer> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.ServiceEndpoint
 */
export declare class ServiceEndpoint extends Message<ServiceEndpoint> {
  /**
   * @generated from field: youtube.response.setting.SetClientSettingEndpoint setClientSettingEndpoint = 81212182;
   */
  setClientSettingEndpoint?: SetClientSettingEndpoint;

  constructor(data?: PartialMessage<ServiceEndpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.ServiceEndpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceEndpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceEndpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceEndpoint;

  static equals(a: ServiceEndpoint | PlainMessage<ServiceEndpoint> | undefined, b: ServiceEndpoint | PlainMessage<ServiceEndpoint> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SetClientSettingEndpoint
 */
export declare class SetClientSettingEndpoint extends Message<SetClientSettingEndpoint> {
  /**
   * @generated from field: youtube.response.setting.SettingData settingData = 1;
   */
  settingData?: SettingData;

  constructor(data?: PartialMessage<SetClientSettingEndpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SetClientSettingEndpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetClientSettingEndpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetClientSettingEndpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetClientSettingEndpoint;

  static equals(a: SetClientSettingEndpoint | PlainMessage<SetClientSettingEndpoint> | undefined, b: SetClientSettingEndpoint | PlainMessage<SetClientSettingEndpoint> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.SettingData
 */
export declare class SettingData extends Message<SettingData> {
  /**
   * @generated from field: youtube.response.setting.ClientSettingEnum clientSettingEnum = 1;
   */
  clientSettingEnum?: ClientSettingEnum;

  /**
   * @generated from field: bool boolValue = 3;
   */
  boolValue: boolean;

  constructor(data?: PartialMessage<SettingData>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.SettingData";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SettingData;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SettingData;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SettingData;

  static equals(a: SettingData | PlainMessage<SettingData> | undefined, b: SettingData | PlainMessage<SettingData> | undefined): boolean;
}

/**
 * @generated from message youtube.response.setting.ClientSettingEnum
 */
export declare class ClientSettingEnum extends Message<ClientSettingEnum> {
  /**
   * @generated from field: int32 item = 1;
   */
  item: number;

  constructor(data?: PartialMessage<ClientSettingEnum>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.setting.ClientSettingEnum";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClientSettingEnum;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClientSettingEnum;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClientSettingEnum;

  static equals(a: ClientSettingEnum | PlainMessage<ClientSettingEnum> | undefined, b: ClientSettingEnum | PlainMessage<ClientSettingEnum> | undefined): boolean;
}

