// @generated by protoc-gen-es v1.7.2
// @generated from file response/setting.proto (package youtube.response.setting, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.setting.Setting
 */
export const Setting = proto3.makeMessageType(
  "youtube.response.setting.Setting",
  () => [
    { no: 6, name: "settingItems", kind: "message", T: SettingItem, repeated: true },
    { no: 10, name: "trackingParams", kind: "message", T: TrackingParams },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingItem
 */
export const SettingItem = proto3.makeMessageType(
  "youtube.response.setting.SettingItem",
  () => [
    { no: 88478200, name: "settingCategoryEntryRenderer", kind: "message", T: SettingCategoryEntryRenderer },
    { no: 66930374, name: "settingCategoryCollectionRenderer", kind: "message", T: SettingCategoryCollectionRenderer },
  ],
);

/**
 * message  St1F7{
 *  SettingCategoryEntryRenderer settingCategoryEntryRenderer = 88478200;
 * }
 *
 * @generated from message youtube.response.setting.TrackingParams
 */
export const TrackingParams = proto3.makeMessageType(
  "youtube.response.setting.TrackingParams",
  () => [
    { no: 1, name: "f1", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "f2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "f3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "timeInfo", kind: "message", T: TimeInfo },
  ],
);

/**
 * @generated from message youtube.response.setting.TimeInfo
 */
export const TimeInfo = proto3.makeMessageType(
  "youtube.response.setting.TimeInfo",
  () => [
    { no: 1, name: "timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */, L: 1 /* LongType.STRING */ },
    { no: 2, name: "f2", kind: "scalar", T: 7 /* ScalarType.FIXED32 */ },
    { no: 3, name: "f3", kind: "scalar", T: 7 /* ScalarType.FIXED32 */ },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingCategoryEntryRenderer
 */
export const SettingCategoryEntryRenderer = proto3.makeMessageType(
  "youtube.response.setting.SettingCategoryEntryRenderer",
  () => [
    { no: 2, name: "f2", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "f3", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "trackingParams", kind: "message", T: TrackingParams },
    { no: 6, name: "f6", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 7, name: "f7", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "f8", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 9, name: "f9", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "f10", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 12, name: "f12", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingCategoryCollectionRenderer
 */
export const SettingCategoryCollectionRenderer = proto3.makeMessageType(
  "youtube.response.setting.SettingCategoryCollectionRenderer",
  () => [
    { no: 3, name: "subSettings", kind: "message", T: SubSetting, repeated: true },
    { no: 4, name: "categoryId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.response.setting.SubSetting
 */
export const SubSetting = proto3.makeMessageType(
  "youtube.response.setting.SubSetting",
  () => [
    { no: 61331416, name: "settingBooleanRenderer", kind: "message", T: SettingBooleanRenderer },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingBooleanRenderer
 */
export const SettingBooleanRenderer = proto3.makeMessageType(
  "youtube.response.setting.SettingBooleanRenderer",
  () => [
    { no: 5, name: "enableServiceEndpoint", kind: "message", T: ServiceEndpoint },
    { no: 6, name: "disableServiceEndpoint", kind: "message", T: ServiceEndpoint },
    { no: 13, name: "clickTrackingParams", kind: "message", T: TrackingParams },
    { no: 15, name: "itemId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.response.setting.ServiceEndpoint
 */
export const ServiceEndpoint = proto3.makeMessageType(
  "youtube.response.setting.ServiceEndpoint",
  () => [
    { no: 2, name: "trackingParams", kind: "message", T: TrackingParams },
    { no: 81212182, name: "setClientSettingEndpoint", kind: "message", T: SetClientSettingEndpoint },
  ],
);

/**
 * @generated from message youtube.response.setting.SetClientSettingEndpoint
 */
export const SetClientSettingEndpoint = proto3.makeMessageType(
  "youtube.response.setting.SetClientSettingEndpoint",
  () => [
    { no: 1, name: "settingDatas", kind: "message", T: SettingDatas },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingDatas
 */
export const SettingDatas = proto3.makeMessageType(
  "youtube.response.setting.SettingDatas",
  () => [
    { no: 1, name: "clientSettingEnum", kind: "message", T: ClientSettingEnum },
    { no: 3, name: "boolValue", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message youtube.response.setting.ClientSettingEnum
 */
export const ClientSettingEnum = proto3.makeMessageType(
  "youtube.response.setting.ClientSettingEnum",
  () => [
    { no: 1, name: "item", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

