// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/setting.proto (package youtube.response.setting, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Label } from "../component/label_pb.js";

/**
 * @generated from message youtube.response.setting.Setting
 */
export const Setting = proto3.makeMessageType(
  "youtube.response.setting.Setting",
  () => [
    { no: 6, name: "settingItems", kind: "message", T: SettingItem, repeated: true },
    { no: 7, name: "CollectionItems", kind: "message", T: SettingItem, repeated: true },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingItem
 */
export const SettingItem = proto3.makeMessageType(
  "youtube.response.setting.SettingItem",
  () => [
    { no: 88478200, name: "backgroundPlayBackSettingRenderer", kind: "message", T: BackgroundPlayBackSettingRenderer },
    { no: 66930374, name: "settingCategoryCollectionRenderer", kind: "message", T: SettingCategoryCollectionRenderer },
  ],
);

/**
 * @generated from message youtube.response.setting.BackgroundPlayBackSettingRenderer
 */
export const BackgroundPlayBackSettingRenderer = proto3.makeMessageType(
  "youtube.response.setting.BackgroundPlayBackSettingRenderer",
  () => [
    { no: 1, name: "name", kind: "message", T: Label },
    { no: 2, name: "backgroundPlayback", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "download", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "trackingParams", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 9, name: "downloadQualitySelection", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 10, name: "smartDownload", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "icon", kind: "message", T: Icon },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingCategoryCollectionRenderer
 */
export const SettingCategoryCollectionRenderer = proto3.makeMessageType(
  "youtube.response.setting.SettingCategoryCollectionRenderer",
  () => [
    { no: 2, name: "name", kind: "message", T: Label },
    { no: 3, name: "subSettings", kind: "message", T: SubSetting, repeated: true },
    { no: 4, name: "categoryId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "icon", kind: "message", T: Icon },
  ],
);

/**
 * @generated from message youtube.response.setting.Icon
 */
export const Icon = proto3.makeMessageType(
  "youtube.response.setting.Icon",
  () => [
    { no: 1, name: "iconType", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.response.setting.SubSetting
 */
export const SubSetting = proto3.makeMessageType(
  "youtube.response.setting.SubSetting",
  () => [
    { no: 61331416, name: "settingBooleanRenderer", kind: "message", T: SettingBooleanRenderer },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingBooleanRenderer
 */
export const SettingBooleanRenderer = proto3.makeMessageType(
  "youtube.response.setting.SettingBooleanRenderer",
  () => [
    { no: 2, name: "title", kind: "message", T: Label },
    { no: 3, name: "description", kind: "message", T: Label },
    { no: 5, name: "enableServiceEndpoint", kind: "message", T: ServiceEndpoint },
    { no: 6, name: "disableServiceEndpoint", kind: "message", T: ServiceEndpoint },
    { no: 15, name: "itemId", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message youtube.response.setting.ServiceEndpoint
 */
export const ServiceEndpoint = proto3.makeMessageType(
  "youtube.response.setting.ServiceEndpoint",
  () => [
    { no: 81212182, name: "setClientSettingEndpoint", kind: "message", T: SetClientSettingEndpoint },
  ],
);

/**
 * @generated from message youtube.response.setting.SetClientSettingEndpoint
 */
export const SetClientSettingEndpoint = proto3.makeMessageType(
  "youtube.response.setting.SetClientSettingEndpoint",
  () => [
    { no: 1, name: "settingData", kind: "message", T: SettingData },
  ],
);

/**
 * @generated from message youtube.response.setting.SettingData
 */
export const SettingData = proto3.makeMessageType(
  "youtube.response.setting.SettingData",
  () => [
    { no: 1, name: "clientSettingEnum", kind: "message", T: ClientSettingEnum },
    { no: 3, name: "boolValue", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message youtube.response.setting.ClientSettingEnum
 */
export const ClientSettingEnum = proto3.makeMessageType(
  "youtube.response.setting.ClientSettingEnum",
  () => [
    { no: 1, name: "item", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

