// @generated by protoc-gen-es v1.7.2
// @generated from file protobuf/response/shorts.proto (package youtube.response.shorts, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message youtube.response.shorts.Shorts
 */
export declare class Shorts extends Message<Shorts> {
  /**
   * @generated from field: repeated youtube.response.shorts.Entry entries = 2;
   */
  entries: Entry[];

  constructor(data?: PartialMessage<Shorts>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.shorts.Shorts";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Shorts;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Shorts;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Shorts;

  static equals(a: Shorts | PlainMessage<Shorts> | undefined, b: Shorts | PlainMessage<Shorts> | undefined): boolean;
}

/**
 * @generated from message youtube.response.shorts.Entry
 */
export declare class Entry extends Message<Entry> {
  /**
   * @generated from field: youtube.response.shorts.Command command = 1;
   */
  command?: Command;

  constructor(data?: PartialMessage<Entry>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.shorts.Entry";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Entry;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Entry;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Entry;

  static equals(a: Entry | PlainMessage<Entry> | undefined, b: Entry | PlainMessage<Entry> | undefined): boolean;
}

/**
 * @generated from message youtube.response.shorts.Command
 */
export declare class Command extends Message<Command> {
  /**
   * @generated from field: youtube.response.shorts.ReelWatchEndpoint reelWatchEndpoint = 139608561;
   */
  reelWatchEndpoint?: ReelWatchEndpoint;

  constructor(data?: PartialMessage<Command>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.shorts.Command";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Command;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Command;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Command;

  static equals(a: Command | PlainMessage<Command> | undefined, b: Command | PlainMessage<Command> | undefined): boolean;
}

/**
 * @generated from message youtube.response.shorts.ReelWatchEndpoint
 */
export declare class ReelWatchEndpoint extends Message<ReelWatchEndpoint> {
  /**
   * @generated from field: youtube.response.shorts.Overlay overlay = 8;
   */
  overlay?: Overlay;

  constructor(data?: PartialMessage<ReelWatchEndpoint>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.shorts.ReelWatchEndpoint";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReelWatchEndpoint;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReelWatchEndpoint;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReelWatchEndpoint;

  static equals(a: ReelWatchEndpoint | PlainMessage<ReelWatchEndpoint> | undefined, b: ReelWatchEndpoint | PlainMessage<ReelWatchEndpoint> | undefined): boolean;
}

/**
 * @generated from message youtube.response.shorts.Overlay
 */
export declare class Overlay extends Message<Overlay> {
  /**
   * @generated from field: youtube.response.shorts.ReelPlayerOverlayRenderer reelPlayerOverlayRenderer = 139970731;
   */
  reelPlayerOverlayRenderer?: ReelPlayerOverlayRenderer;

  constructor(data?: PartialMessage<Overlay>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.shorts.Overlay";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Overlay;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Overlay;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Overlay;

  static equals(a: Overlay | PlainMessage<Overlay> | undefined, b: Overlay | PlainMessage<Overlay> | undefined): boolean;
}

/**
 * @generated from message youtube.response.shorts.ReelPlayerOverlayRenderer
 */
export declare class ReelPlayerOverlayRenderer extends Message<ReelPlayerOverlayRenderer> {
  /**
   * @generated from field: int32 style = 12;
   */
  style: number;

  constructor(data?: PartialMessage<ReelPlayerOverlayRenderer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "youtube.response.shorts.ReelPlayerOverlayRenderer";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ReelPlayerOverlayRenderer;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ReelPlayerOverlayRenderer;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ReelPlayerOverlayRenderer;

  static equals(a: ReelPlayerOverlayRenderer | PlainMessage<ReelPlayerOverlayRenderer> | undefined, b: ReelPlayerOverlayRenderer | PlainMessage<ReelPlayerOverlayRenderer> | undefined): boolean;
}

